<?xml version='1.0' encoding='utf-8'?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.chua</groupId>
        <artifactId>utils-support-parent-starter</artifactId>
        <version>4.0.0.42</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>utils-support-network-parent</artifactId>
    <packaging>pom</packaging>
    <name>Utils Support Network Parent</name>
    <description>网络协议集成父模块：SSH、SFTP、FTP 等</description>
    <modules>
        <module>utils-support-ssh-starter</module>
        <module>utils-support-winrm-starter</module>
        <module>utils-support-ftp-starter</module>
        <module>utils-support-symmetric-starter</module>
        <module>utils-support-vertx-starter</module>
        <module>utils-support-httpclient-starter</module>
        <module>utils-support-netty-starter</module>
        <module>utils-support-okhttp-starter</module>
        <module>utils-support-dht-starter</module>
        <module>utils-support-webdav-starter</module>
        <module>utils-support-rpc-sofa-starter</module>
        <module>utils-support-rpc-json-starter</module>
        <module>utils-support-rpc-dubbo-starter</module>
        <module>utils-support-playwright-starter</module>
        <module>utils-support-armeria-starter</module>
        <module>utils-support-sinch-starter</module>
        <module>utils-support-quarkus-starter</module>
        <module>utils-support-jrebel-starter</module>
        <module>utils-support-socketio-starter</module>
        <module>utils-support-rsocket-starter</module>
        <module>utils-support-acme-starter</module>
        <module>utils-support-tshark-starter</module>
        <module>utils-support-smb-starter</module>
        <module>utils-support-ngrok-starter</module>
        <module>utils-support-git-starter</module>
        <module>utils-support-webview-starter</module>
        <module>utils-support-webview-jcef-starter</module>
    </modules>
    <properties>
        <sshd.version>2.15.0</sshd.version>
        <commons.net.version>3.11.1</commons.net.version>
        <sinch.version>2.0.0</sinch.version>
        <smb.server.version>0.4.0</smb.server.version>
        <smb.jna.version>0.14.0</smb.jna.version>
        <ngrok.version>1.1.1</ngrok.version>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.apache.sshd</groupId>
                <artifactId>sshd-sftp</artifactId>
                <version>${sshd.version}</version>
            </dependency>
            <dependency>
                <groupId>commons-net</groupId>
                <artifactId>commons-net</artifactId>
                <version>${commons.net.version}</version>
            </dependency>
            <dependency>
                <groupId>com.sinch.sdk</groupId>
                <artifactId>sinch-sdk-java</artifactId>
                <version>${sinch.version}</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-all</artifactId>
                <version>${netty.all.version}</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-transport</artifactId>
                <version>${netty.all.version}</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-codec</artifactId>
                <version>${netty.all.version}</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-handler</artifactId>
                <version>${netty.all.version}</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-buffer</artifactId>
                <version>${netty.all.version}</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-common</artifactId>
                <version>${netty.all.version}</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-resolver</artifactId>
                <version>${netty.all.version}</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-transport-native-epoll</artifactId>
                <version>${netty.all.version}</version>
                <classifier>linux-x86_64</classifier>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-transport-native-io_uring</artifactId>
                <version>${netty.all.version}</version>
                <classifier>linux-x86_64</classifier>
            </dependency>
            <dependency>
                <groupId>com.ngrok</groupId>
                <artifactId>ngrok-java</artifactId>
                <version>${ngrok.version}</version>
            </dependency>
            <dependency>
                <groupId>com.ngrok</groupId>
                <artifactId>ngrok-java-native</artifactId>
                <version>${ngrok.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>

