package com.chua.datasource.support.dialect;

import com.chua.common.support.lang.datasource.dialect.Pagination;

/**
 * Oracle 19c+ 方言实现（兼容 12c/11g）。
 *
 * @author CH
 * @since 4.0.0.42
 */
public class OracleDialect extends AbstractDialect {

    /**
     * 支持版本
     */
    public static final String VERSION = "Oracle 19c+ (兼容 12c/11g)";

    @Override
    /** Protocol */
    public String protocol() {
        return "oracle";
    }

    @Override
    /** Driver */
    public String driver() {
        return "oracle.jdbc.OracleDriver";
    }

    @Override
    /** Url */
    public String url() {
        return "jdbc:oracle:thin:@<IP>:<PORT>:<DATABASE>";
    }

    @Override
    /** 打开Quote */
    public char openQuote() {
        return '"';
    }

    @Override
    /** 关闭Quote */
    public char closeQuote() {
        return '"';
    }

    @Override
    /** SupportsLimit */
    public boolean supportsLimit() {
        return true;
    }

    @Override
    /** 处理Sql */
    public String processSql(String sql, Pagination pagination) {
        int offset = pagination.getOffset();
        int limit = pagination.getLimit();
        int end = offset + limit;
        return "SELECT * FROM (SELECT TMP.*, ROWNUM ROW_ID FROM (" + sql + ") TMP WHERE ROWNUM <= " + end
                + ") WHERE ROW_ID > " + offset;
    }

    @Override
    /** 获取TypeName */
    public String getTypeName(int jdbcType, long length, int precision, int scale) {
        return switch (jdbcType) {
            case java.sql.Types.INTEGER -> "NUMBER(10)";
            case java.sql.Types.BIGINT -> "NUMBER(19)";
            case java.sql.Types.SMALLINT -> "NUMBER(5)";
            case java.sql.Types.TINYINT -> "NUMBER(3)";
            case java.sql.Types.VARCHAR -> length > 0 ? "VARCHAR2(" + length + " CHAR)" : "VARCHAR2(255 CHAR)";
            case java.sql.Types.CHAR -> "CHAR(" + length + " CHAR)";
            case java.sql.Types.DECIMAL -> "NUMBER(" + precision + "," + scale + ")";
            case java.sql.Types.DOUBLE -> "FLOAT";
            case java.sql.Types.FLOAT -> "FLOAT";
            case java.sql.Types.BOOLEAN -> "NUMBER(1)";
            case java.sql.Types.TIMESTAMP -> "TIMESTAMP";
            case java.sql.Types.DATE -> "DATE";
            case java.sql.Types.TIME -> "TIMESTAMP";
            case java.sql.Types.CLOB -> "CLOB";
            case java.sql.Types.BLOB -> "BLOB";
            case java.sql.Types.LONGVARCHAR -> "CLOB";
            case java.sql.Types.LONGNVARCHAR -> "CLOB";
            default -> "VARCHAR2(255 CHAR)";
        };
    }

    @Override
    /** 获取AutoIncrementKeyword */
    public String getAutoIncrementKeyword() {
        return "GENERATED BY DEFAULT AS IDENTITY";
    }

    @Override
    /** SupportsUpsert */
    public boolean supportsUpsert() {
        return true;
    }

    @Override
    /** 获取UpsertSql */
    public String getUpsertSql(String tableName, String columns, String values, String updateSet) {
        return "MERGE INTO " + quote(tableName) + " USING DUAL ON (1=0) WHEN NOT MATCHED THEN INSERT ("
                + columns + ") VALUES (" + values + ")";
    }

    @Override
    /** 获取AlterColumnString */
    public String getAlterColumnString() {
        return "MODIFY";
    }

    @Override
    /** 获取CurrentTimestamp选择String */
    public String getCurrentTimestampSelectString() {
        return "SELECT SYSDATE FROM DUAL";
    }

    @Override
    /** 获取写入锁String */
    public String getWriteLockString(int timeout) {
        if (timeout <= 0) {
            return " FOR UPDATE NOWAIT";
        }
        return " FOR UPDATE WAIT " + timeout;
    }

    @Override
    /** 获取DropIndexString */
    public String getDropIndexString(String indexName, String tableName) {
        return "DROP INDEX " + indexName;
    }

    @Override
    /** 获取重命名IndexString */
    public String getRenameIndexString(String oldIndexName, String newIndexName, String tableName) {
        return "ALTER INDEX " + oldIndexName + " RENAME TO " + newIndexName;
    }

    // ==================== 触发器 / 存储过程查询 SQL ====================

    @Override
    /** 获取TriggerListSql */
    public String getTriggerListSql(String schema) {
        StringBuilder sql = new StringBuilder(
                "SELECT TRIGGER_NAME AS trigger_name, OWNER AS trigger_schema, TABLE_NAME AS table_name, "
                        + "TRIGGER_TYPE AS action_timing, TRIGGERING_EVENT AS event_manipulation, "
                        + "STATUS AS status, TRIGGER_BODY AS action_statement "
                        + "FROM ALL_TRIGGERS");
        if (schema != null && !schema.isEmpty()) {
            sql.append(" WHERE OWNER = UPPER('").append(escape(schema)).append("')");
        }
        return sql.toString();
    }

    @Override
    /** 获取TriggerSql */
    public String getTriggerSql(String triggerName, String schema) {
        if (triggerName == null || triggerName.isEmpty()) {
            return null;
        }
        StringBuilder sql = new StringBuilder(
                "SELECT TRIGGER_NAME AS trigger_name, OWNER AS trigger_schema, TABLE_NAME AS table_name, "
                        + "TRIGGER_TYPE AS action_timing, TRIGGERING_EVENT AS event_manipulation, "
                        + "STATUS AS status, TRIGGER_BODY AS action_statement "
                        + "FROM ALL_TRIGGERS WHERE TRIGGER_NAME = '").append(escape(triggerName)).append("'");
        if (schema != null && !schema.isEmpty()) {
            sql.append(" AND OWNER = UPPER('").append(escape(schema)).append("')");
        }
        return sql.toString();
    }

    @Override
    /** 获取ProcedureListSql */
    public String getProcedureListSql(String schema) {
        StringBuilder sql = new StringBuilder(
                "SELECT o.OWNER AS routine_schema, o.OBJECT_NAME AS routine_name, "
                        + "o.OBJECT_TYPE AS routine_type, o.STATUS AS status, "
                        + "(SELECT LISTAGG(s.TEXT, '') WITHIN GROUP (ORDER BY s.LINE) "
                        + "FROM ALL_SOURCE s WHERE s.OWNER = o.OWNER AND s.NAME = o.OBJECT_NAME "
                        + "AND s.TYPE = o.OBJECT_TYPE) AS routine_definition "
                        + "FROM ALL_OBJECTS o WHERE o.OBJECT_TYPE IN ('PROCEDURE', 'FUNCTION')");
        if (schema != null && !schema.isEmpty()) {
            sql.append(" AND o.OWNER = UPPER('").append(escape(schema)).append("')");
        }
        return sql.toString();
    }

    @Override
    /** 获取ProcedureSql */
    public String getProcedureSql(String procedureName, String schema) {
        if (procedureName == null || procedureName.isEmpty()) {
            return null;
        }
        StringBuilder sql = new StringBuilder(
                "SELECT o.OWNER AS routine_schema, o.OBJECT_NAME AS routine_name, "
                        + "o.OBJECT_TYPE AS routine_type, o.STATUS AS status, "
                        + "(SELECT LISTAGG(s.TEXT, '') WITHIN GROUP (ORDER BY s.LINE) "
                        + "FROM ALL_SOURCE s WHERE s.OWNER = o.OWNER AND s.NAME = o.OBJECT_NAME "
                        + "AND s.TYPE = o.OBJECT_TYPE) AS routine_definition "
                        + "FROM ALL_OBJECTS o WHERE o.OBJECT_TYPE IN ('PROCEDURE', 'FUNCTION') "
                        + "AND o.OBJECT_NAME = '").append(escape(procedureName)).append("'");
        if (schema != null && !schema.isEmpty()) {
            sql.append(" AND o.OWNER = UPPER('").append(escape(schema)).append("')");
        }
        return sql.toString();
    }
}
