package com.chua.datasource.support.dialect;

import com.chua.common.support.lang.datasource.dialect.Pagination;
/**
 * @author CH
 */

public class OracleDialect extends AbstractDialect {

    public static final String VERSION = "Oracle 19c+ (兼容 12c/11g)";

    @Override
    public String protocol() {
        return "oracle";
    }

    @Override
    public String driver() {
        return "oracle.jdbc.OracleDriver";
    }

    @Override
    public String url() {
        return "jdbc:oracle:thin:@<IP>:<PORT>:<DATABASE>";
    }

    @Override
    public char openQuote() {
        return '"';
    }

    @Override
    public char closeQuote() {
        return '"';
    }

    @Override
    public boolean supportsLimit() {
        return true;
    }

    @Override
    public String processSql(String sql, Pagination pagination) {
        int offset = pagination.getOffset();
        int limit = pagination.getLimit();
        int end = offset + limit;
        return "SELECT * FROM (SELECT TMP.*, ROWNUM ROW_ID FROM (" + sql + ") TMP WHERE ROWNUM <= " + end
                + ") WHERE ROW_ID > " + offset;
    }

    @Override
    public String getTypeName(int jdbcType, long length, int precision, int scale) {
        return switch (jdbcType) {
            case java.sql.Types.INTEGER -> "NUMBER(10)";
            case java.sql.Types.BIGINT -> "NUMBER(19)";
            case java.sql.Types.SMALLINT -> "NUMBER(5)";
            case java.sql.Types.TINYINT -> "NUMBER(3)";
            case java.sql.Types.VARCHAR -> length > 0 ? "VARCHAR2(" + length + " CHAR)" : "VARCHAR2(255 CHAR)";
            case java.sql.Types.CHAR -> "CHAR(" + length + " CHAR)";
            case java.sql.Types.DECIMAL -> "NUMBER(" + precision + "," + scale + ")";
            case java.sql.Types.DOUBLE -> "FLOAT";
            case java.sql.Types.FLOAT -> "FLOAT";
            case java.sql.Types.BOOLEAN -> "NUMBER(1)";
            case java.sql.Types.TIMESTAMP -> "TIMESTAMP";
            case java.sql.Types.DATE -> "DATE";
            case java.sql.Types.TIME -> "TIMESTAMP";
            case java.sql.Types.CLOB -> "CLOB";
            case java.sql.Types.BLOB -> "BLOB";
            case java.sql.Types.LONGVARCHAR -> "CLOB";
            case java.sql.Types.LONGNVARCHAR -> "CLOB";
            default -> "VARCHAR2(255 CHAR)";
        };
    }

    @Override
    public String getAutoIncrementKeyword() {
        return "GENERATED BY DEFAULT AS IDENTITY";
    }

    @Override
    public boolean supportsUpsert() {
        return true;
    }

    @Override
    public String getUpsertSql(String tableName, String columns, String values, String updateSet) {
        return "MERGE INTO " + quote(tableName) + " USING DUAL ON (1=0) WHEN NOT MATCHED THEN INSERT ("
                + columns + ") VALUES (" + values + ")";
    }

    @Override
    public String getAlterColumnString() {
        return "MODIFY";
    }

    @Override
    public String getCurrentTimestampSelectString() {
        return "SELECT SYSDATE FROM DUAL";
    }

    @Override
    public String getWriteLockString(int timeout) {
        if (timeout <= 0) {
            return " FOR UPDATE NOWAIT";
        }
        return " FOR UPDATE WAIT " + timeout;
    }

    @Override
    public String getDropIndexString(String indexName, String tableName) {
        return "DROP INDEX " + indexName;
    }

    @Override
    public String getRenameIndexString(String oldIndexName, String newIndexName, String tableName) {
        return "ALTER INDEX " + oldIndexName + " RENAME TO " + newIndexName;
    }
}
