package com.chua.datasource.support.dialect;

import com.chua.common.support.lang.datasource.dialect.Pagination;
import com.chua.common.support.lang.datasource.dialect.StorageEngine;

import java.util.Properties;

/**
 * PostgreSQL 14+ 方言实现（兼容 12/13）。
 * <p>所有 SQL 片段、引用符、关键字均可通过 {@link #properties} 覆盖：</p>
 * <ul>
 *   <li>{@code quote-open} / {@code quote-close} — 标识符引用符，默认 {@code "}</li>
 *   <li>{@code auto-increment-keyword} — 自增关键字，默认 {@code GENERATED BY DEFAULT AS IDENTITY}</li>
 *   <li>{@code alter-column-string} — 修改列关键字，默认 {@code ALTER COLUMN}</li>
 *   <li>{@code current-timestamp-sql} — 当前时间查询，默认 {@code SELECT CURRENT_TIMESTAMP}</li>
 *   <li>{@code trigger-list-sql} / {@code trigger-sql} — 触发器查询模板</li>
 *   <li>{@code procedure-list-sql} / {@code procedure-sql} — 存储过程查询模板</li>
 * </ul>
 *
 * @author CH
 * @since 4.0.0.42
 */
public class PostgresqlDialect extends AbstractDialect {

    public static final String VERSION = "PostgreSQL 14+ (兼容 12/13)";

    public PostgresqlDialect() {
    }

    public PostgresqlDialect(Properties properties) {
        withProperties(properties);
    }

    @Override
    public String protocol() {
        return config("protocol", "postgresql");
    }

    @Override
    public String driver() {
        return config("driver", "org.postgresql.Driver");
    }

    @Override
    public String url() {
        return config("url", null);
    }

    @Override
    /** 打开Quote */
    public char openQuote() {
        String v = config("quote-open", "\"");
        return v != null && !v.isEmpty() ? v.charAt(0) : '"';
    }

    @Override
    /** 关闭Quote */
    public char closeQuote() {
        String v = config("quote-close", "\"");
        return v != null && !v.isEmpty() ? v.charAt(0) : '"';
    }

    @Override
    /** 处理Sql */
    public String processSql(String sql, Pagination pagination) {
        return sql + " LIMIT " + pagination.getLimit() + " OFFSET " + pagination.getOffset();
    }

    @Override
    /** 获取TypeName */
    public String getTypeName(int jdbcType, long length, int precision, int scale) {
        return switch (jdbcType) {
            case java.sql.Types.INTEGER -> "INTEGER";
            case java.sql.Types.BIGINT -> "BIGINT";
            case java.sql.Types.SMALLINT -> "SMALLINT";
            case java.sql.Types.TINYINT -> "SMALLINT";
            case java.sql.Types.VARCHAR -> length > 0 ? "VARCHAR(" + length + ")" : "VARCHAR(255)";
            case java.sql.Types.CHAR -> "CHAR(" + length + ")";
            case java.sql.Types.DECIMAL -> "NUMERIC(" + precision + "," + scale + ")";
            case java.sql.Types.DOUBLE -> "DOUBLE PRECISION";
            case java.sql.Types.FLOAT -> "REAL";
            case java.sql.Types.BOOLEAN -> "BOOLEAN";
            case java.sql.Types.TIMESTAMP -> "TIMESTAMP";
            case java.sql.Types.DATE -> "DATE";
            case java.sql.Types.TIME -> "TIME";
            case java.sql.Types.CLOB -> "TEXT";
            case java.sql.Types.BLOB -> "BYTEA";
            case java.sql.Types.LONGVARCHAR -> "TEXT";
            case java.sql.Types.LONGNVARCHAR -> "TEXT";
            default -> "VARCHAR(255)";
        };
    }

    @Override
    /** 获取AutoIncrementKeyword */
    public String getAutoIncrementKeyword() {
        return config("auto-increment-keyword", "GENERATED BY DEFAULT AS IDENTITY");
    }

    @Override
    /** SupportsUpsert */
    public boolean supportsUpsert() {
        return true;
    }

    @Override
    /** 获取UpsertSql */
    public String getUpsertSql(String tableName, String columns, String values, String updateSet) {
        return "insert into " + quote(tableName) + " (" + columns + ") values (" + values
                + ") on conflict do update set " + updateSet;
    }

    @Override
    /** 获取AlterColumnString */
    public String getAlterColumnString() {
        return config("alter-column-string", "ALTER COLUMN");
    }

    @Override
    /** 获取CurrentTimestamp选择String */
    public String getCurrentTimestampSelectString() {
        return config("current-timestamp-sql", "SELECT CURRENT_TIMESTAMP");
    }

    @Override
    /** 获取TableComment */
    public String getTableComment(String comment) {
        return config("table-comment", "");
    }

    @Override
    /** 获取ColumnComment */
    public String getColumnComment(String comment) {
        return config("column-comment", "");
    }

    @Override
    /** 原生向量支持检测（需 pgvector 扩展） */
    public boolean supportsVector() {
        // PostgreSQL 本身支持，但需额外安装 pgvector 扩展；
        // 默认视为支持，建表失败时由 VectorStorage fallback 处理
        return true;
    }

    @Override
    /** JSON 支持（JSON/JSONB 自 9.2 起） */
    public boolean supportsJson() {
        return true;
    }

    // ==================== 触发器 / 存储过程查询 SQL ====================

    @Override
    /** 获取TriggerListSql */
    public String getTriggerListSql(String schema) {
        String template = config("trigger-list-sql", null);
        if (template != null) {
            if (schema != null && !schema.isEmpty()) {
                return template.replace(":schema", "'" + escape(schema) + "'");
            }
            return template;
        }
        StringBuilder sql = new StringBuilder(
                "SELECT t.tgname AS trigger_name, n.nspname AS trigger_schema, c.relname AS table_name, "
                        + "CASE WHEN t.tgtype::int & 2 <> 0 THEN 'BEFORE' "
                        + "     WHEN t.tgtype::int & 64 <> 0 THEN 'INSTEAD OF' ELSE 'AFTER' END AS action_timing, "
                        + "CASE WHEN t.tgtype::int & 4 <> 0 THEN 'INSERT' "
                        + "     WHEN t.tgtype::int & 8 <> 0 THEN 'DELETE' "
                        + "     WHEN t.tgtype::int & 16 <> 0 THEN 'UPDATE' "
                        + "     WHEN t.tgtype::int & 32 <> 0 THEN 'TRUNCATE' END AS event_manipulation, "
                        + "pg_get_triggerdef(t.oid) AS action_statement "
                        + "FROM pg_trigger t "
                        + "JOIN pg_class c ON c.oid = t.tgrelid "
                        + "JOIN pg_namespace n ON n.oid = c.relnamespace "
                        + "WHERE NOT t.tgisinternal");
        if (schema != null && !schema.isEmpty()) {
            sql.append(" AND n.nspname = '").append(escape(schema)).append("'");
        }
        return sql.toString();
    }

    @Override
    /** 获取TriggerSql */
    public String getTriggerSql(String triggerName, String schema) {
        if (triggerName == null || triggerName.isEmpty()) {
            return null;
        }
        return "SELECT * FROM (" + getTriggerListSql(schema) + ") T "
                + "WHERE trigger_name = '" + escape(triggerName) + "'";
    }

    @Override
    /** 获取ProcedureListSql */
    public String getProcedureListSql(String schema) {
        String template = config("procedure-list-sql", null);
        if (template != null) {
            if (schema != null && !schema.isEmpty()) {
                return template.replace(":schema", "'" + escape(schema) + "'");
            }
            return template;
        }
        StringBuilder sql = new StringBuilder(
                "SELECT n.nspname AS routine_schema, p.proname AS routine_name, "
                        + "CASE p.prokind WHEN 'p' THEN 'PROCEDURE' ELSE 'FUNCTION' END AS routine_type, "
                        + "pg_get_function_result(p.oid) AS data_type, "
                        + "pg_get_functiondef(p.oid) AS routine_definition "
                        + "FROM pg_proc p "
                        + "JOIN pg_namespace n ON n.oid = p.pronamespace "
                        + "WHERE p.prokind IN ('p', 'f') "
                        + "AND n.nspname NOT IN ('pg_catalog', 'information_schema')");
        if (schema != null && !schema.isEmpty()) {
            sql.append(" AND n.nspname = '").append(escape(schema)).append("'");
        }
        return sql.toString();
    }

    @Override
    /** 获取ProcedureSql */
    public String getProcedureSql(String procedureName, String schema) {
        if (procedureName == null || procedureName.isEmpty()) {
            return null;
        }
        return "SELECT * FROM (" + getProcedureListSql(schema) + ") T "
                + "WHERE routine_name = '" + escape(procedureName) + "'";
    }
}
