<?xml version='1.0' encoding='utf-8'?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.chua</groupId>
        <artifactId>utils-support-parent-starter</artifactId>
        <version>4.0.0.42</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>utils-support-extra-parent</artifactId>
    <packaging>pom</packaging>
    <name>Utils Support Extra Parent</name>
    <description>扩展模块父模块：ASM、AST、验证码、AppImage 等</description>
    <modules>
        <module>utils-support-asm-starter</module>
        <module>utils-support-appimage-starter</module>
        <module>utils-support-ast-starter</module>
        <module>utils-support-captcha-starter</module>
        <module>utils-support-desktop-starter</module>
        <module>utils-support-enhance-starter</module>
        <module>utils-support-jdk15on-starter</module>
        <module>utils-support-multipart-starter</module>
        <module>utils-support-oshi-starter</module>
        
        <module>utils-support-metrics-starter</module>
        <module>utils-support-serialize-starter</module>
        <module>utils-support-fory-starter</module>
        <module>utils-support-protobuf-starter</module>
        <module>utils-support-gson-starter</module>
        <module>utils-support-fastjson-starter</module>
        <module>utils-support-tika-starter</module>
        <module>utils-support-tui-starter</module>
        <module>utils-support-video-processor-starter</module>
        <module>utils-support-example-starter</module>
    </modules>
</project>
