package com.chua.datasource.support.flyway;

import com.chua.common.support.lang.datasource.flyway.DefaultScriptConverter;
import com.chua.common.support.spi.annotations.Spi;

import java.util.regex.Pattern;

/**
 * Derby 迁移脚本方言转换器（{@code ScriptConverter} 的 derby 协议实现）。
 *
 * <p>本类放在 {@code utils-support-datasource-starter} 而不是独立的
 * {@code utils-support-derby-starter}：仓库中并不存在 derby 专属 starter 模块，
 * 唯一的 Derby 方言类即本类本身，独立成模块会形成只有一个类的空壳模块。</p>
 *
 * <h3>与 MySQL 源方言的具体差异</h3>
 * <p>项目脚本统一按 MySQL 风格书写，Derby 的类型体系很窄（SQL 标准 1999 子集 + 自增扩展），
 * 与 MySQL 的差异主要有四类，本类逐条处理：</p>
 * <ol>
 *   <li><b>类型体系窄</b>：Derby 没有 {@code TINYINT}/{@code MEDIUMINT}/{@code DATETIME}/
 *       {@code TEXT}/{@code JSON}，也没有 {@code VARBINARY}；数值类型
 *       （{@code SMALLINT}/{@code INTEGER}/{@code BIGINT}）<b>不接受长度修饰</b>，
 *       {@code INT(11)} 属于语法错误</li>
 *   <li><b>没有行内索引</b>：{@code ENGINE=}、{@code AUTO_INCREMENT=}、{@code CHARSET=}、
 *       {@code COLLATE=}、内联 {@code COMMENT}、行内 {@code KEY}/{@code UNIQUE KEY} 都是 MySQL 专属</li>
 *   <li><b>没有 upsert 语法</b>：{@code INSERT IGNORE}、{@code ON DUPLICATE KEY UPDATE} 都不是 Derby 语法</li>
 *   <li><b>函数命名不同</b>：Derby 无 {@code NOW()}、无 {@code IFNULL()}</li>
 * </ol>
 *
 * <h3>逐条规则与依据</h3>
 * <ol>
 *   <li>{@code ENGINE=} / {@code AUTO_INCREMENT=} / {@code CHARSET=} / {@code COLLATE=} /
 *       内联 {@code COMMENT} / 行内 {@code KEY} / {@code UNIQUE KEY}：已由
 *       {@link DefaultScriptConverter} 的表尾属性、行内索引、列内联注释三组规则剥离，
 *       本类不重复实现，只在其之上再补一条 {@code USING BTREE} 剥离。
 *       依据：这些子句全部是 {@code SHOW CREATE TABLE} 导出风格，Derby 解析器一律报语法错误。
 *       补充 {@code USING BTREE} 的原因是：整行的 {@code KEY ... USING BTREE} 已被父类整行删除，
 *       但<b>独立的 {@code CREATE INDEX idx ON tbl(col) USING BTREE} 语句</b>不在父类剥离范围内，
 *       而 Derby 的 {@code CREATE INDEX} 只有 {@code CREATE [UNIQUE] INDEX name ON table (cols)} 一种形态，
 *       多写 {@code USING BTREE} 会直接语法错误</li>
 *   <li>{@code ON UPDATE CURRENT_TIMESTAMP} → 剥离。依据：这是 MySQL 独有的列属性自动更新时间机制，
 *       Derby 既无此语法也无等价机制，列不会自动更新（派生值应由触发器或应用层维护）</li>
 *   <li>类型映射：{@code TINYINT}→{@code SMALLINT}（Derby 最小整数类型即 2 字节 {@code SMALLINT}）；
 *       {@code MEDIUMINT}→{@code INTEGER}（3 字节无对应类型，取上界 4 字节避免溢出）；
 *       {@code DATETIME}→{@code TIMESTAMP}（Derby 无独立 DATETIME 类型）；
 *       {@code MEDIUMTEXT}/{@code LONGTEXT}/{@code TINYTEXT}/{@code TEXT}/{@code JSON}→
 *       {@code VARCHAR(4000)}；{@code BINARY}/{@code VARBINARY}→{@code BLOB}。
 *       <b>文本类为何写 VARCHAR(4000) 而不是 CLOB</b>：Derby 的 CLOB 列是 LOB 类型，
 *       不能出现在 {@code CREATE TABLE} 的默认值约束上、不能参与唯一索引、不能直接与字符串字面量比较，
 *       而 MySQL 风格脚本里这些列普遍带 {@code NOT NULL DEFAULT ''}，
 *       改写成 CLOB 会让建表直接失败；{@code VARCHAR(4000)} 在 Derby 上（上限 32672 字符）既能建表可执行，
 *       又保留了可比较、可建索引的语义。<b>代价</b>：超长文本会被截断或报错，
 *       若业务确实要存大文本，请在脚本中直接按 Derby 原生语法写 {@code CLOB}。
 *       {@code DOUBLE} 保持原样——Derby 原生支持 {@code DOUBLE} 类型名，无需映射。
 *       <b>数值类型长度修饰必须一并剥离</b>：本项目脚本普遍写 {@code TINYINT(1)}，
 *       若只把 {@code TINYINT} 换成 {@code SMALLINT}，结果是 {@code SMALLINT(1)}，
 *       而 Derby 的 {@code SMALLINT}/{@code INTEGER}/{@code BIGINT} 都不接受长度修饰，仍是语法错误，
 *       因此额外剥离 {@code TINYINT(1)}/{@code INT(11)}/{@code BIGINT(20)} 的显示宽度</li>
 *   <li>函数映射：{@code NOW()}→{@code CURRENT_TIMESTAMP}、{@code IFNULL(}→{@code COALESCE(}。
 *       依据：Derby 的当前时间是无括号关键字 {@code CURRENT_TIMESTAMP}，两参数空值合并是标准
 *       {@code COALESCE}</li>
 *   <li>{@code INSERT IGNORE} → 整条返回 {@code null} 跳过。
 *       依据：Derby 没有「忽略冲突」插入语法，{@code INSERT OR REPLACE} 语义并不等价
 *       （后者会覆盖已有行）。跳过而不是改写，是因为这批 {@code INSERT} 都是初始化数据
 *       （{@code db/initdata}）里的兜底/脏数据清理语句，缺一条不影响建表与主流程；
 *       而错误地改写成 {@code INSERT OR REPLACE} 会静默覆盖用户已改过的初始化数据，风险更高</li>
 *   <li>{@code AUTO_INCREMENT} → 仅剥离关键字。
 *       <b>依据与取舍</b>：Derby 的自增写法是列级 {@code GENERATED BY DEFAULT AS IDENTITY}
 *       （或表级 {@code GENERATED ALWAYS AS IDENTITY (...)}），而把列级关键字下推需要预知主键列名
 *       与表级主键声明的对应关系（参考 {@code SqliteScriptConverter} 的下推逻辑），
 *       写错会造成双主键或语义漂移。<b>因此本转换器只保证「建表可执行」</b>：
 *       {@code AUTO_INCREMENT} 被剥掉后该列不再自动编号。
 *       Derby 自增请直接在脚本里写 IDENTITY 语法，或在应用层显式赋值</li>
 * </ol>
 *
 * <h3>已知未覆盖项（有意不做）</h3>
 * <p>{@code ON DUPLICATE KEY UPDATE}：Derby 同样不支持，但它不在本转换器的处理规则内，
 * 当前按原样透传（会在 Derby 上报语法错误）。理由是 Derby 的等价 upsert 只能写成
 * {@code MERGE INTO ... USING ... WHEN MATCHED THEN UPDATE}，
 * 需要预知主键列才能构造匹配的 {@code USING} 子句，属于高风险改写，不在本次保守映射范围内。
 * 若脚本含该写法，请手工改写为 {@code MERGE} 或由应用层保证唯一性后改用「先查后插」。</p>
 *
 * <h3>扩展键与前提</h3>
 * <p>扩展键必须等于协议名（{@code @Spi("derby")} + 本模块
 * {@code META-INF/extensions/com.chua.common.support.lang.datasource.flyway.ScriptConverter}
 * 中的 {@code derby=} 行）：因为 {@code ScriptConverter} 的 {@code getExtension(protocol)}
 * 是先按协议名精确查扩展键，再用兜底默认实现；若扩展键与协议名不同（哪怕写成 SPI 名称
 * {@code script-converter}），就只能在兜底遍历里被 {@code @SpiDefault} 同键遮蔽，
 * 本类的增强规则永远不会被命中。</p>
 *
 * <p>前提与 {@link DefaultScriptConverter} 一致：{@code CREATE TABLE} 按<b>每列一行</b>的对齐格式书写
 * （行内索引各占一行，列定义内联 {@code COMMENT} 在行尾）。
 * 本类的行级规则（{@code USING BTREE}、{@code AUTO_INCREMENT} 剥离）都依赖行尾锚定，
 * 单行紧凑写法的 {@code CREATE TABLE} 不在转换范围内。</p>
 *
 * @author CH
 * @since 4.0.0.42
 */
@Spi(value = DerbyScriptConverter.PROTOCOL, order = 100)
public class DerbyScriptConverter extends DefaultScriptConverter {

    /**
     * 本协议名（同时作为 SPI 扩展键，见本模块 {@code META-INF/extensions/...ScriptConverter}）
     */
    public static final String PROTOCOL = "derby";

    /**
     * 独立 {@code CREATE INDEX ... USING BTREE} 语句尾部的 {@code USING BTREE} 子句。
     * 依据：Derby 的 {@code CREATE INDEX} 不接受索引实现方式子句；行内 {@code KEY ... USING BTREE}
     * 已被 {@link DefaultScriptConverter} 整行剥离，此处只补独立索引语句这一种残留形态。
     */
    private static final Pattern USING_BTREE = Pattern.compile(
            "(?i)\\s+USING\\s+BTREE\\s*(,?)\\s*$", Pattern.MULTILINE);

    /**
     * 列定义中的 {@code ON UPDATE CURRENT_TIMESTAMP}（MySQL 专属，Derby 无此语法与等价机制）
     */
    private static final Pattern ON_UPDATE_CURRENT_TIMESTAMP = Pattern.compile(
            "(?i)\\s+ON\\s+UPDATE\\s+CURRENT_TIMESTAMP");

    /**
     * {@code INSERT IGNORE}（MySQL 专属，Derby 无「忽略冲突」插入语法，整条跳过）
     * 锚定在语句起始行首，避免误伤 {@code INSERT ... ON DUPLICATE ...} 之类的其它形态
     */
    private static final Pattern INSERT_IGNORE = Pattern.compile(
            "(?is)^\\s*INSERT\\s+IGNORE\\b");

    /**
     * 任意位置的 {@code AUTO_INCREMENT} 关键字（含表尾 {@code AUTO_INCREMENT=100} 形式）。
     * 仅剥离关键字，不改写为 Derby 的 {@code GENERATED BY DEFAULT AS IDENTITY}
     */
    private static final Pattern AUTO_INCREMENT_TOKEN = Pattern.compile(
            "\\s*\\bAUTO_INCREMENT\\b(\\s*=\\s*\\d+)?", Pattern.CASE_INSENSITIVE);

    /**
     * 数值类型的显示宽度修饰（{@code TINYINT(1)} / {@code INT(11)} / {@code BIGINT(20)}）。
     * 依据：Derby 的 {@code SMALLINT}/{@code INTEGER}/{@code BIGINT} 不接受长度修饰，
     * 不剥离则类型映射后的 {@code SMALLINT(1)} 仍是语法错误。
     * 替换为 {@code $1}（裸类型名），不改变精度语义（数值类型长度本就是 MySQL 的显示宽度）
     */
    private static final Pattern NUMERIC_DISPLAY_WIDTH = Pattern.compile(
            "(?i)\\b(TINYINT|SMALLINT|MEDIUMINT|INT|INTEGER|BIGINT)\\s*\\(\\s*\\d+\\s*\\)");

    /**
     * {@code TINYINT}（MySQL 1 字节无符号小整数）→ Derby 最小整数类型 {@code SMALLINT}
     */
    private static final Pattern TINYINT_TYPE = Pattern.compile("(?i)\\bTINYINT\\b");

    /**
     * {@code MEDIUMINT}（3 字节）→ Derby 无对应类型，取上界 {@code INTEGER} 避免溢出
     */
    private static final Pattern MEDIUMINT_TYPE = Pattern.compile("(?i)\\bMEDIUMINT\\b");

    /**
     * {@code DATETIME} → Derby 无独立 DATETIME 类型，统一落到 {@code TIMESTAMP}
     */
    private static final Pattern DATETIME_TYPE = Pattern.compile("(?i)\\bDATETIME\\b");

    /**
     * MySQL 文本族 → {@code VARCHAR(4000)}。
     * 分支顺序必须长类型在前：若先匹配到 {@code TEXT}，{@code MEDIUMTEXT}/{@code LONGTEXT}/{@code TINYTEXT}
     * 会被截成 {@code MEDIAVARCHAR(4000)} 这类坏串
     */
    private static final Pattern TEXT_TYPE = Pattern.compile(
            "(?i)\\b(?:MEDIUMTEXT|LONGTEXT|TINYTEXT|TEXT)\\b");

    /**
     * {@code JSON} → {@code VARCHAR(4000)}。
     * 与文本族同映射，理由见类注释：Derby 的 CLOB 不能带 DEFAULT、不能建唯一索引
     */
    private static final Pattern JSON_TYPE = Pattern.compile("(?i)\\bJSON\\b");

    /**
     * Derby 文本族统一落地类型（{@code VARCHAR} 上限 32672 字符，4000 兼顾建表可执行与语义可比较）
     */
    private static final String DERBY_TEXT_TYPE = "VARCHAR(4000)";

    /**
     * {@code BINARY} / {@code VARBINARY} → Derby 二进制大对象 {@code BLOB}。
     * 两条规则可合并：{@code \bBINARY\b} 不会命中 {@code VARBINARY}（{@code VAR} 与 {@code BINARY} 之间无单词边界）
     */
    private static final Pattern BINARY_TYPE = Pattern.compile("(?i)\\b(?:VAR)?BINARY\\b");

    /**
     * MySQL {@code NOW()} → Derby {@code CURRENT_TIMESTAMP}（无括号关键字）
     */
    private static final Pattern NOW_FUNCTION = Pattern.compile("(?i)\\bNOW\\s*\\(\\s*\\)");

    /**
     * MySQL {@code IFNULL(} → 标准 {@code COALESCE(}
     */
    private static final Pattern IFNULL_FUNCTION = Pattern.compile("(?i)\\bIFNULL\\s*\\(");

    /**
     * 剥离子句后可能遗留的悬挂逗号（列定义被整段移除时的尾逗号）
     */
    private static final Pattern DANGLING_COMMA = Pattern.compile(",\\s*\\)");

    @Override
    public boolean supports(String protocol) {
        return PROTOCOL.equalsIgnoreCase(protocol);
    }

    @Override
    public String convert(String statement, String protocol) {
        // 先走父类：剥离表尾 MySQL 属性、行内 KEY/UNIQUE KEY、列内联 COMMENT、列级 CHARSET/COLLATE
        String converted = super.convert(statement, protocol);
        if (converted == null || converted.isBlank()) {
            return converted;
        }
        // INSERT IGNORE 在 Derby 上无等价语法且改写语义不等价，整条跳过
        if (INSERT_IGNORE.matcher(converted).find()) {
            return null;
        }
        // 补剥离父类未覆盖的 USING BTREE（主要是独立的 CREATE INDEX 语句）
        converted = USING_BTREE.matcher(converted).replaceAll("$1");
        converted = ON_UPDATE_CURRENT_TIMESTAMP.matcher(converted).replaceAll("");
        // AUTO_INCREMENT 只剥关键字：Derby 自增须显式写 IDENTITY，本转换器只保证建表可执行
        converted = AUTO_INCREMENT_TOKEN.matcher(converted).replaceAll("");
        // 类型映射：先剥数值显示宽度（Derby 数值类型无长度修饰），再做类型名替换
        converted = NUMERIC_DISPLAY_WIDTH.matcher(converted).replaceAll("$1");
        converted = TINYINT_TYPE.matcher(converted).replaceAll("SMALLINT");
        converted = MEDIUMINT_TYPE.matcher(converted).replaceAll("INTEGER");
        converted = DATETIME_TYPE.matcher(converted).replaceAll("TIMESTAMP");
        converted = TEXT_TYPE.matcher(converted).replaceAll(DERBY_TEXT_TYPE);
        converted = JSON_TYPE.matcher(converted).replaceAll(DERBY_TEXT_TYPE);
        converted = BINARY_TYPE.matcher(converted).replaceAll("BLOB");
        // 函数映射
        converted = NOW_FUNCTION.matcher(converted).replaceAll("CURRENT_TIMESTAMP");
        converted = IFNULL_FUNCTION.matcher(converted).replaceAll("COALESCE(");
        // 收尾：修正常量替换后遗留的悬挂逗号
        return DANGLING_COMMA.matcher(converted).replaceAll(")");
    }
}
