<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.chua</groupId>
        <artifactId>utils-support-datatask-parent</artifactId>
        <version>4.0.0.42</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>utils-support-datasync-starter</artifactId>
    <packaging>jar</packaging>
    <name>DataSync Server Starter</name>
    <description>DataSync Server锛歁apping銆佽皟搴︺€佹墽琛屽櫒銆丄gentServer 绠＄悊</description>

    <build>
        <plugins>
            
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>com.chua</groupId>
            <artifactId>utils-support-datasync-agent-starter</artifactId>
            <version>4.0.0.42</version>
        </dependency>
        <dependency>
            <groupId>org.yaml</groupId>
            <artifactId>snakeyaml</artifactId>
            <version>2.4</version>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.26.3</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-test</artifactId>
            <version>3.6.11</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
