package com.chua.postgresql.support.ddl;

import com.chua.common.support.lang.datasource.engine.ddl.ColumnDef;
import com.chua.common.support.lang.datasource.engine.ddl.DdlProvider;
import com.chua.common.support.spi.annotations.Spi;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

/**
 * PostgreSQL 方言 DDL 生成器。
 *
 * <p>PostgreSQL 不支持 {@code CREATE DATABASE IF NOT EXISTS}，建库语句改用
 * {@code DO} 匿名块捕获 {@code duplicate_database} 异常实现幂等；建表用
 * 双引号包裹标识符（内部双引号双写转义），自增列使用
 * {@code GENERATED BY DEFAULT AS IDENTITY}。列注释在 PG 中是独立的
 * {@code COMMENT ON} 语句，不并入单条建表 DDL。</p>
 *
 * @author CH
 * @since 4.0.0.43
 */
@Spi(DdlProvider.SPI_NAME)
public class PostgresqlDdlProvider implements DdlProvider {

    /**
     * 本实现覆盖的方言协议。
     */
    private static final Set<String> PROTOCOLS = Set.of("postgresql", "postgresql9", "postgresql10");

    /**
     * 判断是否支持给定数据库方言协议。
     *
     * @param protocol 方言协议名
     * @return 是否支持该协议
     */
    @Override
    public boolean supports(String protocol) {
        return protocol != null && PROTOCOLS.contains(protocol);
    }

    /**
     * 生成建库语句。
     *
     * @param dbName 数据库名称
     * @return 完整的建库 DDL 语句
     */
    @Override
    public String createDatabase(String dbName) {
        return "DO $$ BEGIN CREATE DATABASE " + quote(dbName)
                + "; EXCEPTION WHEN duplicate_database THEN NULL; END $$;";
    }

    /**
     * 生成删库语句。
     *
     * @param dbName 数据库名称
     * @return 完整的删库 DDL 语句
     */
    @Override
    public String dropDatabase(String dbName) {
        return "DROP DATABASE IF EXISTS " + quote(dbName);
    }

    /**
     * 生成建表语句。
     *
     * @param tableName 表名
     * @param columns   列定义列表
     * @return 完整的建表 DDL 语句
     */
    @Override
    public String createTable(String tableName, List<ColumnDef> columns) {
        if (columns == null || columns.isEmpty()) {
            throw new IllegalArgumentException("建表列定义不能为空: " + tableName);
        }
        StringBuilder sb = new StringBuilder("CREATE TABLE IF NOT EXISTS ")
                .append(quote(tableName)).append(" (\n");
        List<String> pk = new ArrayList<>();
        List<String> defs = new ArrayList<>();
        for (ColumnDef col : columns) {
            if (col.getName() == null || col.getName().isBlank()) {
                throw new IllegalArgumentException("建表列名不能为空: " + tableName);
            }
            StringBuilder def = new StringBuilder("  ").append(quote(col.getName())).append(' ')
                    .append(col.getType() == null || col.getType().isBlank() ? "VARCHAR(255)" : col.getType());
            if (col.isAutoIncrement()) {
                def.append(" GENERATED BY DEFAULT AS IDENTITY");
            }
            if (col.isPrimaryKey() || !col.isNullable()) {
                def.append(" NOT NULL");
            }
            if (col.getDefaultValue() != null && !col.getDefaultValue().isBlank()) {
                def.append(" DEFAULT ").append(col.getDefaultValue());
            }
            if (col.isPrimaryKey()) {
                pk.add(quote(col.getName()));
            }
            defs.add(def.toString());
        }
        sb.append(String.join(",\n", defs));
        if (!pk.isEmpty()) {
            sb.append(",\n  PRIMARY KEY (").append(String.join(", ", pk)).append(")");
        }
        return sb.append("\n)").toString();
    }

    /**
     * 双引号包裹标识符，内部双引号双写转义。
     *
     * @param identifier 标识符原始值
     * @return 字符串
     */
    private static String quote(String identifier) {
        if (identifier == null || identifier.isBlank()) {
            throw new IllegalArgumentException("DDL 标识符不能为空");
        }
        return "\"" + identifier.replace("\"", "\"\"") + "\"";
    }
}
