Args = --initialize-at-build-time=org.slf4j \
	-H:IncludeResources=META-INF/services/.* \
	-H:IncludeResources=META-INF/extensions/.* \
	--enable-url-protocols=http,https

JavaArgs = -Dfile.encoding=UTF-8