package com.chua.common.support.image.png;

import javax.imageio.IIOException;
import javax.imageio.ImageReadParam;
import javax.imageio.ImageReader;
import javax.imageio.ImageTypeSpecifier;
import javax.imageio.metadata.IIOMetadata;
import javax.imageio.spi.ImageReaderSpi;
import javax.imageio.stream.ImageInputStream;
import java.awt.*;
import java.awt.color.ColorSpace;
import java.awt.image.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.zip.Inflater;
import java.util.zip.InflaterInputStream;

import static com.chua.common.support.image.png.PNG.*;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
/**
   * 类 png镜像数据enumeration implements Enumeration<InputStream> {
 *
 * @author CH
 * @since 4.0.0.42
 */



class PNGImageDataEnumeration implements Enumeration<InputStream> {

    boolean firstTime = true; // 第一个时间
    ImageInputStream stream; // 流
    int length; // 长度
    final boolean fdAT; // fdat

    /**
      * 创建 png镜像数据enumeration 实例
     * @param stream 流
     * @param fdAT fdat
     */
    public PNGImageDataEnumeration(ImageInputStream stream, boolean fdAT)
        throws IOException {
        this.stream = stream;
        this.length = stream.readInt();
 // 跳过 chunk 类型
        stream.skipBytes(4);
        int type = stream.readInt();
        this.fdAT = fdAT;
        if (fdAT) {
            stream.readInt();
        }
    }

    @Override
    /** 下一个element */
    public InputStream nextElement() {
        try {
            firstTime = false;
            ImageInputStream iis = new SubImageInputStream(stream, length - (fdAT ? 4 : 0));
            return new InputStreamAdapter(iis);
        } catch (IOException e) {
            return null;
        }
    }

    @Override
    /** 是否拥有moreelements */
    public boolean hasMoreElements() {
        if (firstTime) {
            return true;
        }
        try {
            int crc = stream.readInt();
            this.length = stream.readInt();
            int type = stream.readInt();
            if (fdAT) {
                stream.readInt();
                return type == PNGImageReader.fdAT_TYPE;
            }
            else {
                return type == PNGImageReader.IDAT_TYPE;
            }
        } catch (IOException e) {
            return false;
        }
    }
}

/**
 * PNG 图像读取器。
 *
 * <p>基于 JDK Image I/O 框架实现的 PNG 格式图像读取器，
 * 支持标准 PNG 规范的各项特性，包括透明度、伽马校正、ICC 色彩配置等。</p>
 *
 * @author CH
 * @since 4.0.0.42
 */
public class PNGImageReader extends ImageReader {

    /*
      * 笔记: The following chunk 类型 常量 are autogenerated.  Each
      * one 是否 derived 从 the ASCII 值 的 its 4-character 名称.  For
      * example, IHDR_类型 是否 calculated as follows:
     *            ('I' << 24) | ('H' << 16) | ('D' << 8) | 'R'
     */

    // Critical chunks
    static final int IHDR_TYPE = 0x49484452;
    static final int PLTE_TYPE = 0x504c5445; // plte类型
    static final int IDAT_TYPE = 0x49444154; // idat类型
    static final int IEND_TYPE = 0x49454e44; // iend类型

    // Ancillary chunks
    static final int tRNS_TYPE = 0x74524e53;

    static final int cHRM_TYPE = 0x6348524d; // chrm类型
    static final int gAMA_TYPE = 0x67414d41; // gama类型
    static final int iCCP_TYPE = 0x69434350; // iccp类型
    static final int sBIT_TYPE = 0x73424954; // s钻头类型
    static final int sRGB_TYPE = 0x73524742; // srgb类型
    static final int cICP_TYPE = 0x63494350; // cicp类型

    static final int iTXt_TYPE = 0x69545874; // itxt类型
    static final int tEXt_TYPE = 0x74455874; // 文本类型
    static final int zTXt_TYPE = 0x7a545874; // ztxt类型

    static final int bKGD_TYPE = 0x624b4744; // bkgd类型
    static final int hIST_TYPE = 0x68495354; // hist类型
    static final int pHYs_TYPE = 0x70485973; // phys类型
    static final int sPLT_TYPE = 0x73504c54; // splt类型
    static final int eXIf_TYPE = 0x65584966; // exif类型

    static final int tIME_TYPE = 0x74494d45; // 时间类型
    static final int acTL_TYPE = 0x6163544C; // actl类型
    static final int fcTL_TYPE = 0x6663544C; // 函数计算tl类型
    static final int fdAT_TYPE = 0x66644154; // fdat类型

 // The 数字 的 bands by PNG color 类型
    static final int[] inputBandsForColorType = {
         // 1, // gray
   
        // -1, // unused
    
         // 3, // rgb
   
         // 1, // palette
   
         // 2, // gray + alpha
   
        // -1, // unused
    
         // 4  // rgb + alpha
   
    };

    static final int[] adam7XOffset = { 0, 4, 0, 2, 0, 1, 0 }; // adam7x偏移量
    static final int[] adam7YOffset = { 0, 0, 4, 0, 2, 0, 1 }; // adam7y偏移量
    static final int[] adam7XSubsampling = { 8, 8, 4, 4, 2, 2, 1, 1 }; // adam7xsubsampling
    static final int[] adam7YSubsampling = { 8, 8, 8, 4, 4, 2, 2, 1 }; // adam7ysubsampling

    //private static final boolean debug = true;

    boolean isAnimated; // 是否animated

    ImageInputStream stream = null; // 流

    boolean gotHeader = false; // got头部
    boolean gotMetadata = false; // gotmetadata

    //ImageReadParam lastParam = null;

    long imageStartPosition = -1L; // 镜像启动位置
    Map<Integer, PNGMetadata> frameMetadata = new HashMap<>(); // 帧metadata
    Map<Integer, Long> frameImageStartPositions = new HashMap<>(); // 帧镜像启动位置
    int nextImageIndex = 0; // 下一个镜像索引

    Rectangle sourceRegion = null; // 源region
    int sourceXSubsampling = -1; // 源xsubsampling
    int sourceYSubsampling = -1; // 源ysubsampling
    int sourceMinProgressivePass = 0; // 源最小进步通过
    int sourceMaxProgressivePass = 6; // 源最大进步通过
    int[] sourceBands = null; // 源bands
    int[] destinationBands = null; // 目标bands
    Point destinationOffset = new Point(0, 0); // 目标偏移量

    PNGMetadata metadata = new PNGMetadata(); // metadata

    DataInputStream pixelStream = null; // pixel流

    BufferedImage theImage = null; // the镜像

 // The 数字 的 源 pixels 处理
    int pixelsDone = 0;

 // The total 数字 的 pixels 入 the 源 镜像
    int totalPixels;

    boolean animContainsIDAT = false; // animcontainsidat

    /**
      * 创建 png镜像读取 实例
     * @param originatingProvider originating提供者
     */
    public PNGImageReader(ImageReaderSpi originatingProvider) {
        super(originatingProvider);
    }

    @Override
    /**
      * 设置输入
     * @param input 输入
     * @param seekForwardOnly seek远期only
     * @param ignoreMetadata ignoremetadata
     */
    public void setInput(Object input,
                         boolean seekForwardOnly,
                         boolean ignoreMetadata) {
        super.setInput(input, seekForwardOnly, ignoreMetadata);
        this.stream = (ImageInputStream) input;

 // Clear 全部 值 基础 on the 上一个 流 内容
        resetStreamSettings();
    }

    /**
      * 读取空terminated字符串
     * @param charset 字符集
     * @param maxLen 最大len
     * @return 读取空terminated字符串的结果
     */
    private String readNullTerminatedString(String charset, int maxLen) throws IOException {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        int b = 0;
        int count = 0;
        while ((maxLen > count++) && ((b = stream.read()) != 0)) {
            if (b == -1) {
                throw new EOFException();
            }
            baos.write(b);
        }
        if (b != 0) {
            throw new IIOException("Found non null terminated string");
        }
        return baos.toString(charset);
    }

    /** 读取头部 */
    private void readHeader() throws IIOException {
        if (gotHeader) {
            return;
        }
        if (stream == null) {
            throw new IllegalStateException("Input source not set!");
        }

        try {
            byte[] signature = new byte[8];
            stream.readFully(signature);

            if (signature[0] != (byte)137 ||
                signature[1] != (byte)80 ||
                signature[2] != (byte)78 ||
                signature[3] != (byte)71 ||
                signature[4] != (byte)13 ||
                signature[5] != (byte)10 ||
                signature[6] != (byte)26 ||
                signature[7] != (byte)10) {
                throw new IIOException("Bad PNG signature!");
            }

            int IHDR_length = stream.readInt();
            if (IHDR_length != 13) {
                throw new IIOException("Bad length for IHDR chunk!");
            }
            int IHDR_type = stream.readInt();
            if (IHDR_type != IHDR_TYPE) {
                throw new IIOException("Bad type for IHDR chunk!");
            }

            this.metadata = new PNGMetadata();

            int width = stream.readInt();
            int height = stream.readInt();

 // Re-use 签名 array 转为 bulk-读取 these unsigned byte 值
            stream.readFully(signature, 0, 5);
            int bitDepth          = signature[0] & 0xff;
            int colorType         = signature[1] & 0xff;
            int compressionMethod = signature[2] & 0xff;
            int filterMethod      = signature[3] & 0xff;
            int interlaceMethod   = signature[4] & 0xff;

 // 跳过 IHDR CRC
            stream.skipBytes(4);

            stream.flushBefore(stream.getStreamPosition());

            if (width <= 0) {
                throw new IIOException("Image width <= 0!");
            }
            if (height <= 0) {
                throw new IIOException("Image height <= 0!");
            }
            if (bitDepth != 1 && bitDepth != 2 && bitDepth != 4 &&
                bitDepth != 8 && bitDepth != 16) {
                throw new IIOException("Bit depth must be 1, 2, 4, 8, or 16!");
            }
            if (colorType != 0 && colorType != 2 && colorType != 3 &&
                colorType != 4 && colorType != 6) {
                throw new IIOException("Color type must be 0, 2, 3, 4, or 6!");
            }
            if (colorType == PNG_COLOR_PALETTE && bitDepth == 16) {
                throw new IIOException("Bad color type/bit depth combination!");
            }
            if ((colorType == PNG_COLOR_RGB ||
                 colorType == PNG_COLOR_RGB_ALPHA ||
                 colorType == PNG_COLOR_GRAY_ALPHA) &&
                (bitDepth != 8 && bitDepth != 16)) {
                throw new IIOException("Bad color type/bit depth combination!");
            }
            if (compressionMethod != 0) {
                throw new IIOException("Unknown compression method (not 0)!");
            }
            if (filterMethod != 0) {
                throw new IIOException("Unknown filter method (not 0)!");
            }
            if (interlaceMethod != 0 && interlaceMethod != 1) {
                throw new IIOException("Unknown interlace method (not 0 or 1)!");
            }

            metadata.IHDR_present = true;
            metadata.IHDR_width = width;
            metadata.IHDR_height = height;
            metadata.IHDR_bitDepth = bitDepth;
            metadata.IHDR_colorType = colorType;
            metadata.IHDR_compressionMethod = compressionMethod;
            metadata.IHDR_filterMethod = filterMethod;
            metadata.IHDR_interlaceMethod = interlaceMethod;

            gotHeader = true;
        } catch (IOException e) {
            throw new IIOException("I/O error reading PNG header!", e);
        }
    }

    /** 解析actchunk */
    private void parse_acTL_chunk() throws IOException {
        if (metadata.acTL_present) {
            processWarningOccurred(
"An APNG image may not contain more than one acTL chunk.\n" +
"The chunk wil be ignored.");
            stream.skipBytes(8);
            return;
        }
        metadata.acTL_num_frames = stream.readInt();
        metadata.acTL_num_plays = stream.readInt();

        isAnimated = true;
        metadata.acTL_present = true;
    }

    /** 解析函数计算tchunk */
    private void parse_fcTL_chunk() throws IOException {
        if (!frameMetadata.containsKey(nextImageIndex)) {
            PNGMetadata metadata = new PNGMetadata();
            frameMetadata.put(nextImageIndex, metadata);
        }
        PNGMetadata metadata = frameMetadata.get(nextImageIndex);
        if (metadata.fcTL_present) {
            processWarningOccurred(
"An APNG image frame may not contain more than one fcTL chunk.\n" +
"The chunk wil be ignored.");
            stream.skipBytes(26);
            return;
        }
        metadata.fcTL_sequence_number = stream.readInt();
        metadata.fcTL_width = stream.readInt();
        metadata.fcTL_height = stream.readInt();
        metadata.fcTL_x_offset = stream.readInt();
        metadata.fcTL_y_offset = stream.readInt();
        metadata.fcTL_delay_num = stream.readUnsignedShort();
        metadata.fcTL_delay_den = stream.readUnsignedShort();
        metadata.fcTL_dispose_op = stream.readUnsignedByte();
        metadata.fcTL_blend_op = stream.readUnsignedByte();

        metadata.fcTL_present = true;
        nextImageIndex ++;
    }

    /**
      * 解析pltchunk
     * @param chunkLength chunk长度
     */
    private void parse_PLTE_chunk(int chunkLength) throws IOException {
        if (metadata.PLTE_present) {
            processWarningOccurred(
"A PNG image may not contain more than one PLTE chunk.\n" +
"The chunk wil be ignored.");
            return;
        } else if (metadata.IHDR_colorType == PNG_COLOR_GRAY ||
                   metadata.IHDR_colorType == PNG_COLOR_GRAY_ALPHA) {
            processWarningOccurred(
"A PNG gray or gray alpha image cannot have a PLTE chunk.\n" +
"The chunk wil be ignored.");
            return;
        }

        byte[] palette = new byte[chunkLength];
        stream.readFully(palette);

        int numEntries = chunkLength/3;
        if (metadata.IHDR_colorType == PNG_COLOR_PALETTE) {
            int maxEntries = 1 << metadata.IHDR_bitDepth;
            if (numEntries > maxEntries) {
                processWarningOccurred(
"PLTE chunk contains too many entries for bit depth, ignoring extras.");
                numEntries = maxEntries;
            }
            numEntries = Math.min(numEntries, maxEntries);
        }

 // Round array 大小 up 转为 2^2^n
        int paletteEntries;
        if (numEntries > 16) {
            paletteEntries = 256;
        } else if (numEntries > 4) {
            paletteEntries = 16;
        } else if (numEntries > 2) {
            paletteEntries = 4;
        } else {
            paletteEntries = 2;
        }

        metadata.PLTE_present = true;
        metadata.PLTE_red = new byte[paletteEntries];
        metadata.PLTE_green = new byte[paletteEntries];
        metadata.PLTE_blue = new byte[paletteEntries];

        int index = 0;
        for (int i = 0; i < numEntries; i++) {
            metadata.PLTE_red[i] = palette[index++];
            metadata.PLTE_green[i] = palette[index++];
            metadata.PLTE_blue[i] = palette[index++];
        }
    }

    /** 解析bkgchunk */
    private void parse_bKGD_chunk() throws IOException {
        if (metadata.IHDR_colorType == PNG_COLOR_PALETTE) {
            metadata.bKGD_colorType = PNG_COLOR_PALETTE;
            metadata.bKGD_index = stream.readUnsignedByte();
        } else if (metadata.IHDR_colorType == PNG_COLOR_GRAY ||
                   metadata.IHDR_colorType == PNG_COLOR_GRAY_ALPHA) {
            metadata.bKGD_colorType = PNG_COLOR_GRAY;
            metadata.bKGD_gray = stream.readUnsignedShort();
        } else {
            // RGB 或 RGB_ALPHA
            metadata.bKGD_colorType = PNG_COLOR_RGB;
            metadata.bKGD_red = stream.readUnsignedShort();
            metadata.bKGD_green = stream.readUnsignedShort();
            metadata.bKGD_blue = stream.readUnsignedShort();
        }

        metadata.bKGD_present = true;
    }

    /** 解析chrchunk */
    private void parse_cHRM_chunk() throws IOException {
        metadata.cHRM_whitePointX = stream.readInt();
        metadata.cHRM_whitePointY = stream.readInt();
        metadata.cHRM_redX = stream.readInt();
        metadata.cHRM_redY = stream.readInt();
        metadata.cHRM_greenX = stream.readInt();
        metadata.cHRM_greenY = stream.readInt();
        metadata.cHRM_blueX = stream.readInt();
        metadata.cHRM_blueY = stream.readInt();

        metadata.cHRM_present = true;
    }

    /** 解析gamchunk */
    private void parse_gAMA_chunk() throws IOException {
        int gamma = stream.readInt();
        metadata.gAMA_gamma = gamma;

        metadata.gAMA_present = true;
    }

    /**
     * 解析h是否chunk
     * @param chunkLength chunk长度
     */
    private void parse_hIST_chunk(int chunkLength) throws IOException {
        if (!metadata.PLTE_present) {
            throw new IIOException("hIST chunk without prior PLTE chunk!");
        }

        /* According to PNG specification length of
          * hist chunk 是否 specified 入 bytes 和
          * hist chunk consists 的 2 byte elements
          * (so we 期望 长度 是否 even).
         */
        metadata.hIST_histogram = new char[chunkLength/2];
        stream.readFully(metadata.hIST_histogram,
                         0, metadata.hIST_histogram.length);

        metadata.hIST_present = true;
    }

    /**
      * 解析iccchunk
     * @param chunkLength chunk长度
     */
    private void parse_iCCP_chunk(int chunkLength) throws IOException {
        String keyword = readNullTerminatedString("ISO-8859-1", 80);
        int compressedProfileLength = chunkLength - keyword.length() - 2;
        if (compressedProfileLength <= 0) {
            throw new IIOException("iCCP chunk length is not proper");
        }
        metadata.iCCP_profileName = keyword;

        metadata.iCCP_compressionMethod = stream.readUnsignedByte();

        byte[] compressedProfile =
          new byte[compressedProfileLength];
        stream.readFully(compressedProfile);
        metadata.iCCP_compressedProfile = compressedProfile;

        metadata.iCCP_present = true;
    }

    /**
      * 解析itxtchunk
     * @param chunkLength chunk长度
     */
    private void parse_iTXt_chunk(int chunkLength) throws IOException {
        long chunkStart = stream.getStreamPosition();

        String keyword = readNullTerminatedString("ISO-8859-1", 80);
        metadata.iTXt_keyword.add(keyword);

        int compressionFlag = stream.readUnsignedByte();
        metadata.iTXt_compressionFlag.add(Boolean.valueOf(compressionFlag == 1));

        int compressionMethod = stream.readUnsignedByte();
        metadata.iTXt_compressionMethod.add(Integer.valueOf(compressionMethod));

        long pos = stream.getStreamPosition();
        int remainingLen = (int)(chunkStart + chunkLength - pos);
        String languageTag = readNullTerminatedString("UTF8", remainingLen);
        metadata.iTXt_languageTag.add(languageTag);

        pos = stream.getStreamPosition();
        remainingLen = (int)(chunkStart + chunkLength - pos);
        if (remainingLen < 0) {
            throw new IIOException("iTXt chunk length is not proper");
        }
        String translatedKeyword =
            readNullTerminatedString("UTF8", remainingLen);
        metadata.iTXt_translatedKeyword.add(translatedKeyword);

        String text;
        pos = stream.getStreamPosition();
        int textLength = (int)(chunkStart + chunkLength - pos);
        if (textLength < 0) {
            throw new IIOException("iTXt chunk length is not proper");
        }
        byte[] b = new byte[textLength];
        stream.readFully(b);

        if (compressionFlag == 1) {
            // 解压文本
            text = new String(inflate(b), StandardCharsets.UTF_8);
        } else {
            text = new String(b, StandardCharsets.UTF_8);
        }
        metadata.iTXt_text.add(text);

 // 检查 if the 文本 chunk contains 镜像 创建 时间
        if (keyword.equals(PNGMetadata.tEXt_creationTimeKey)) {
 // 更新 标准/文档/镜像创建时间 从 文本 chunk
            int index = metadata.iTXt_text.size() - 1;
            metadata.decodeImageCreationTimeFromTextChunk(
                    metadata.iTXt_text.listIterator(index));
        }
    }

    /** 解析physchunk */
    private void parse_pHYs_chunk() throws IOException {
        metadata.pHYs_pixelsPerUnitXAxis = stream.readInt();
        metadata.pHYs_pixelsPerUnitYAxis = stream.readInt();
        metadata.pHYs_unitSpecifier = stream.readUnsignedByte();

        metadata.pHYs_present = true;
    }

    /** 解析sbichunk */
    private void parse_sBIT_chunk() throws IOException {
        int colorType = metadata.IHDR_colorType;
        if (colorType == PNG_COLOR_GRAY ||
            colorType == PNG_COLOR_GRAY_ALPHA) {
            metadata.sBIT_grayBits = stream.readUnsignedByte();
        } else if (colorType == PNG_COLOR_RGB ||
                   colorType == PNG_COLOR_PALETTE ||
                   colorType == PNG_COLOR_RGB_ALPHA) {
            metadata.sBIT_redBits = stream.readUnsignedByte();
            metadata.sBIT_greenBits = stream.readUnsignedByte();
            metadata.sBIT_blueBits = stream.readUnsignedByte();
        }

        if (colorType == PNG_COLOR_GRAY_ALPHA ||
            colorType == PNG_COLOR_RGB_ALPHA) {
            metadata.sBIT_alphaBits = stream.readUnsignedByte();
        }

        metadata.sBIT_colorType = colorType;
        metadata.sBIT_present = true;
    }

    /**
      * 解析splchunk
     * @param chunkLength chunk长度
     */
    private void parse_sPLT_chunk(int chunkLength)
        throws IOException {
        metadata.sPLT_paletteName = readNullTerminatedString("ISO-8859-1", 80);
        int remainingChunkLength = chunkLength -
                (metadata.sPLT_paletteName.length() + 1);
        if (remainingChunkLength <= 0) {
            throw new IIOException("sPLT chunk length is not proper");
        }

        int sampleDepth = stream.readUnsignedByte();
        metadata.sPLT_sampleDepth = sampleDepth;

        int numEntries = remainingChunkLength/(4*(sampleDepth/8) + 2);
        metadata.sPLT_red = new int[numEntries];
        metadata.sPLT_green = new int[numEntries];
        metadata.sPLT_blue = new int[numEntries];
        metadata.sPLT_alpha = new int[numEntries];
        metadata.sPLT_frequency = new int[numEntries];

        if (sampleDepth == 8) {
            for (int i = 0; i < numEntries; i++) {
                metadata.sPLT_red[i] = stream.readUnsignedByte();
                metadata.sPLT_green[i] = stream.readUnsignedByte();
                metadata.sPLT_blue[i] = stream.readUnsignedByte();
                metadata.sPLT_alpha[i] = stream.readUnsignedByte();
                metadata.sPLT_frequency[i] = stream.readUnsignedShort();
            }
        } else if (sampleDepth == 16) {
            for (int i = 0; i < numEntries; i++) {
                metadata.sPLT_red[i] = stream.readUnsignedShort();
                metadata.sPLT_green[i] = stream.readUnsignedShort();
                metadata.sPLT_blue[i] = stream.readUnsignedShort();
                metadata.sPLT_alpha[i] = stream.readUnsignedShort();
                metadata.sPLT_frequency[i] = stream.readUnsignedShort();
            }
        } else {
            throw new IIOException("sPLT sample depth not 8 or 16!");
        }

        metadata.sPLT_present = true;
    }

    /** 解析srgchunk */
    private void parse_sRGB_chunk() throws IOException {
        metadata.sRGB_renderingIntent = stream.readUnsignedByte();

        metadata.sRGB_present = true;
    }

    /** 解析cicchunk */
    private void parse_cICP_chunk() throws IOException {
        metadata.cICP_colourPrimaries = stream.readUnsignedByte();
        metadata.cICP_transferFunction = stream.readUnsignedByte();
        metadata.cICP_matrixCoefficients = stream.readUnsignedByte();
        metadata.cICP_videoFullRangeFlag = stream.readUnsignedByte() == 1;

        metadata.cICP_present = true;
    }

    /**
      * 解析textchunk
     * @param chunkLength chunk长度
     */
    private void parse_tEXt_chunk(int chunkLength) throws IOException {
        String keyword = readNullTerminatedString("ISO-8859-1", 80);
        int textLength = chunkLength - keyword.length() - 1;
        if (textLength < 0) {
            throw new IIOException("tEXt chunk length is not proper");
        }
        metadata.tEXt_keyword.add(keyword);

        byte[] b = new byte[textLength];
        stream.readFully(b);
        metadata.tEXt_text.add(new String(b, StandardCharsets.ISO_8859_1));

 // 检查 if the 文本 chunk contains 镜像 创建 时间
        if (keyword.equals(PNGMetadata.tEXt_creationTimeKey)) {
 // 更新 标准/文档/镜像创建时间 从 文本 chunk
            int index = metadata.tEXt_text.size() - 1;
            metadata.decodeImageCreationTimeFromTextChunk(
                    metadata.tEXt_text.listIterator(index));
        }
    }

    /** 解析timchunk */
    private void parse_tIME_chunk() throws IOException {
        metadata.tIME_year = stream.readUnsignedShort();
        metadata.tIME_month = stream.readUnsignedByte();
        metadata.tIME_day = stream.readUnsignedByte();
        metadata.tIME_hour = stream.readUnsignedByte();
        metadata.tIME_minute = stream.readUnsignedByte();
        metadata.tIME_second = stream.readUnsignedByte();

        metadata.tIME_present = true;
    }

    /**
      * 解析trnchunk
     * @param chunkLength chunk长度
     */
    private void parse_tRNS_chunk(int chunkLength) throws IOException {
        int colorType = metadata.IHDR_colorType;
        if (colorType == PNG_COLOR_PALETTE) {
            if (!metadata.PLTE_present) {
                processWarningOccurred(
"tRNS chunk without prior PLTE chunk, ignoring it.");
                return;
            }

            // Alpha table may have fewer entries than RGB palette
            int maxEntries = metadata.PLTE_red.length;
            int numEntries = chunkLength;
            if (numEntries > maxEntries && maxEntries > 0) {
                processWarningOccurred(
"tRNS chunk has more entries than prior PLTE chunk, ignoring extras.");
                numEntries = maxEntries;
            }
            metadata.tRNS_alpha = new byte[numEntries];
            metadata.tRNS_colorType = PNG_COLOR_PALETTE;
            stream.read(metadata.tRNS_alpha, 0, numEntries);
            stream.skipBytes(chunkLength - numEntries);
        } else if (colorType == PNG_COLOR_GRAY) {
            if (chunkLength != 2) {
                processWarningOccurred(
"tRNS chunk for gray image must have length 2, ignoring chunk.");
                stream.skipBytes(chunkLength);
                return;
            }
            metadata.tRNS_gray = stream.readUnsignedShort();
            metadata.tRNS_colorType = PNG_COLOR_GRAY;
        } else if (colorType == PNG_COLOR_RGB) {
            if (chunkLength != 6) {
                processWarningOccurred(
"tRNS chunk for RGB image must have length 6, ignoring chunk.");
                stream.skipBytes(chunkLength);
                return;
            }
            metadata.tRNS_red = stream.readUnsignedShort();
            metadata.tRNS_green = stream.readUnsignedShort();
            metadata.tRNS_blue = stream.readUnsignedShort();
            metadata.tRNS_colorType = PNG_COLOR_RGB;
        } else {
            processWarningOccurred(
"Gray+Alpha and RGBS images may not have a tRNS chunk, ignoring it.");
            return;
        }

        metadata.tRNS_present = true;
    }

    /**
     * inflate。
     * @param b b
     * @return inflate的结果
     */
    private static byte[] inflate(byte[] b) throws IOException {
        InputStream bais = new ByteArrayInputStream(b);
        InputStream iis = new InflaterInputStream(bais);
        ByteArrayOutputStream baos = new ByteArrayOutputStream();

        int c;
        try {
            while ((c = iis.read()) != -1) {
                baos.write(c);
            }
        } finally {
            iis.close();
        }
        return baos.toByteArray();
    }

    /**
      * 解析exifchunk
     * @param chunkLength chunk长度
     */
    private void parse_eXIf_chunk(int chunkLength) throws IOException {
        byte[] b = new byte[chunkLength];
        stream.readFully(b);
        metadata.eXIf_data = b;

        metadata.eXIf_present = true;
    }

    /**
      * 解析ztxtchunk
     * @param chunkLength chunk长度
     */
    private void parse_zTXt_chunk(int chunkLength) throws IOException {
        String keyword = readNullTerminatedString("ISO-8859-1", 80);
        int textLength = chunkLength - keyword.length() - 2;
        if (textLength < 0) {
            throw new IIOException("zTXt chunk length is not proper");
        }
        metadata.zTXt_keyword.add(keyword);

        int method = stream.readUnsignedByte();
        metadata.zTXt_compressionMethod.add(method);

        byte[] b = new byte[textLength];
        stream.readFully(b);
        metadata.zTXt_text.add(new String(inflate(b), StandardCharsets.ISO_8859_1));

 // 检查 if the 文本 chunk contains 镜像 创建 时间
        if (keyword.equals(PNGMetadata.tEXt_creationTimeKey)) {
 // 更新 标准/文档/镜像创建时间 从 文本 chunk
            int index = metadata.zTXt_text.size() - 1;
            metadata.decodeImageCreationTimeFromTextChunk(
                    metadata.zTXt_text.listIterator(index));
        }
    }

    /** 读取Metadata */
    private void readMetadata() throws IIOException {
        if (gotMetadata) {
            return;
        }
        readHeader();

        /*
          * Optimization: We 能否 跳过 读取 metadata if ignoremetadata
          * flag 是否 设置 和 color类型 是否 not PNG_COLOR_PALETTE. However,
          * we 解析 trns chunk 转为 retrieve the transparent color 从 the
          * metadata. 执行 so, helps png镜像读取 转为 appropriately
          * identify 和 设置 transparent pixels 入 the decoded 镜像 for
          * color类型 PNG_COLOR_RGB 和 PNG_COLOR_GRAY.
         */
        int colorType = metadata.IHDR_colorType;
        if (ignoreMetadata && colorType != PNG_COLOR_PALETTE) {
            try {
                while (true) {
                    int chunkLength = stream.readInt();

 // 验证 the chunk 长度 第一个
                    if (chunkLength < 0 || chunkLength + 4 < 0) {
                        throw new IIOException("Invalid chunk length " + chunkLength);
                    }

                    int chunkType = stream.readInt();

                    if (chunkType == acTL_TYPE) {
                        parse_acTL_chunk();
                    } else if (isAnimated && chunkType == fcTL_TYPE) {
                        if (imageStartPosition == -1L) {
                            animContainsIDAT = true;
                        }
                        parse_fcTL_chunk();
                    } else if (isAnimated && chunkType == fdAT_TYPE) {
                        int sequenceNumber = stream.readInt();
                        stream.skipBytes(-12);
                        int index = nextImageIndex - 1;
                        if (!frameImageStartPositions.containsKey(index)) {
                            if (!frameMetadata.containsKey(index)) {
                                throw new IIOException("Required fcTL chunk missing");
                            }
                            PNGMetadata metadata = frameMetadata.get(index);
                            metadata.fdAT_present = true;
                            metadata.fdAT_sequence_number = sequenceNumber;
                            frameImageStartPositions.put(index, stream.getStreamPosition());
                        }
                    } else if (chunkType == IDAT_TYPE) {
                        // We've reached the first IDAT chunk position
                        stream.skipBytes(-8);
                        imageStartPosition = stream.getStreamPosition();
                        /*
                          * According 转为 PNG specification trns chunk must
                          * precede the 第一个 IDAT chunk. So we 能否 停止
                          * 读取 metadata.
                         */
                        break;
                    } else if (chunkType == tRNS_TYPE) {
                        parse_tRNS_chunk(chunkLength);
 // 之后 解析 trns chunk we will 跳过 4 CRC bytes
                        stream.skipBytes(4);
                    } else {
 // 跳过 the chunk plus the 4 CRC bytes that follow
                        stream.skipBytes(chunkLength + 4);
                    }
                }
            } catch (IOException e) {
                throw new IIOException("Error skipping PNG metadata", e);
            }

            gotMetadata = true;
            return;
        }

        try {
            loop: while (true) {
                int chunkLength = stream.readInt();
                int chunkType = stream.readInt();
 // 初始化 chunkcrc, 值 assigned 是否包含 no significance
                int chunkCRC = -1;

 // 验证 the chunk 长度
                if (chunkLength < 0) {
                    throw new IIOException("Invalid chunk length " + chunkLength);
                }

                try {
                    /*
                      * As per PNG specification 全部 chunks should have
                      * 4 byte CRC. But there are some 镜像 where
                      * CRC 是否 not present/corrupt for IEND chunk.
                      * 和 these 类型 的 镜像 are 支持 by other
                      * 解码器. So as soon as we hit chunk 类型
                      * for IEND chunk 停止 读取 metadata.
                     */
                    if (chunkType != IEND_TYPE) {
                        stream.mark();
                        stream.seek(stream.getStreamPosition() + chunkLength);
                        chunkCRC = stream.readInt();
                        stream.reset();
                    }
                } catch (IOException e) {
                    throw new IIOException("Invalid chunk length " + chunkLength);
                }

                switch (chunkType) {
                case acTL_TYPE:
                    parse_acTL_chunk();
                    break;
                case fcTL_TYPE:
                    if (imageStartPosition == -1L) {
                        animContainsIDAT = true;
                    }
                    parse_fcTL_chunk();
                    break;
                case fdAT_TYPE:
                    int sequenceNumber = stream.readInt();

                    /*
                      * The PNG specification mandates that if color类型 是否
                      * PNG_COLOR_PALETTE 然后 the PLTE chunk should appear
                      * 之前 the 第一个 IDAT chunk.
                     */
                    if (colorType == PNG_COLOR_PALETTE &&
                            !(metadata.PLTE_present)) {
                        {
                        throw new IIOException("Required PLTE chunk"
                        + " missing");
                        }
                        int index = nextImageIndex - 1;
                    }
                    if (!frameImageStartPositions.containsKey(index)) {
                        if (!frameMetadata.containsKey(index)) {
                            throw new IIOException("Required fcTL chunk missing");
                        }
                        PNGMetadata metadata = frameMetadata.get(index);
                        metadata.fdAT_present = true;
                        metadata.fdAT_sequence_number = sequenceNumber;
                        frameImageStartPositions.put(index, stream.getStreamPosition() - 12);
                    }
 // Move.com.com 转为 the CRC byte 位置.
                    stream.skipBytes(chunkLength - 4);
                    break;
                case IDAT_TYPE:
                    // If chunk type is 'IDAT', we've reached the image data.
                    if (imageStartPosition == -1L) {
                        /*
                          * The PNG specification mandates that if color类型 是否
                          * PNG_COLOR_PALETTE 然后 the PLTE chunk should appear
                          * 之前 the 第一个 IDAT chunk.
                         */
                        if (colorType == PNG_COLOR_PALETTE &&
                            !(metadata.PLTE_present)) {
                            {
                            throw new IIOException("Required PLTE chunk"
                            + " missing");
                            }
                            /*
                            * pngs may contain 多个 IDAT chunks containing
                            * a portion 的 镜像 数据. We 存储 the 位置 的
                            * the 第一个 IDAT chunk 和 继续 with 迭代
                            * 的 other chunks that follow 镜像 数据.
                            */
                            imageStartPosition = stream.getStreamPosition() - 8;
                        }
                    }
 // Move.com.com 转为 the CRC byte 位置.
                    stream.skipBytes(chunkLength);
                    break;
                case IEND_TYPE:
                    /*
                      * If the chunk 类型 是否 'IEND', we've reached 结束 的 镜像.
                      * Seek 转为 the 第一个 IDAT chunk for subsequent decoding.
                     */
                    stream.seek(imageStartPosition);

                    /*
                      * flush之前 discards the portion 的 the 流 之前
                      * the indicated 位置. Hence this should be used 之后
                      * we 完成 迭代 over 可用 chunks including
                      * those that appear 之后 the IDAT.
                     */
                    stream.flushBefore(stream.getStreamPosition());
                    break loop;
                case PLTE_TYPE:
                    parse_PLTE_chunk(chunkLength);
                    break;
                case bKGD_TYPE:
                    parse_bKGD_chunk();
                    break;
                case cHRM_TYPE:
                    parse_cHRM_chunk();
                    break;
                case gAMA_TYPE:
                    parse_gAMA_chunk();
                    break;
                case hIST_TYPE:
                    parse_hIST_chunk(chunkLength);
                    break;
                case iCCP_TYPE:
                    parse_iCCP_chunk(chunkLength);
                    break;
                case iTXt_TYPE:
                    if (ignoreMetadata) {
                        stream.skipBytes(chunkLength);
                    } else {
                        parse_iTXt_chunk(chunkLength);
                    }
                    break;
                case pHYs_TYPE:
                    parse_pHYs_chunk();
                    break;
                case sBIT_TYPE:
                    parse_sBIT_chunk();
                    break;
                case sPLT_TYPE:
                    parse_sPLT_chunk(chunkLength);
                    break;
                case sRGB_TYPE:
                    parse_sRGB_chunk();
                    break;
                case cICP_TYPE:
                    parse_cICP_chunk();
                    break;
                case tEXt_TYPE:
                    parse_tEXt_chunk(chunkLength);
                    break;
                case tIME_TYPE:
                    parse_tIME_chunk();
                    break;
                case tRNS_TYPE:
                    parse_tRNS_chunk(chunkLength);
                    break;
                case eXIf_TYPE:
                    if (ignoreMetadata) {
                        stream.skipBytes(chunkLength);
                    } else {
                        parse_eXIf_chunk(chunkLength);
                    }
                    break;
                case zTXt_TYPE:
                    if (ignoreMetadata) {
                        stream.skipBytes(chunkLength);
                    } else {
                        parse_zTXt_chunk(chunkLength);
                    }
                    break;
                default:
 // 读取 an unknown chunk
                    byte[] b = new byte[chunkLength];
                    stream.readFully(b);

                    String chunkName = String.valueOf((char) (chunkType >>> 24)) +
                            (char) ((chunkType >> 16) & 0xff) +
                            (char) ((chunkType >> 8) & 0xff) +
                            (char) (chunkType & 0xff);

                    int ancillaryBit = chunkType >>> 28;
                    if (ancillaryBit == 0) {
                        processWarningOccurred(
"Encountered unknown chunk with critical bit set!");
                    }

                    metadata.unknownChunkType.add(chunkName);
                    metadata.unknownChunkData.add(b);
                    break;
                }

 // double 检查 whether 全部 chunk 数据 were consumed
                if (chunkCRC != stream.readInt()) {
                    throw new IIOException("Failed to read a chunk of type " +
                            chunkType);
                }
            }
        } catch (IOException e) {
            throw new IIOException("Error reading PNG metadata", e);
        }

        gotMetadata = true;
    }

 // 数据 过滤器 方法

    private static void decodeSubFilter(byte[] curr, int coff, int count,
                                        int bpp) {
        for (int i = bpp; i < count; i++) {
            int val;

            val = curr[i + coff] & 0xff;
            val += curr[i + coff - bpp] & 0xff;

            curr[i + coff] = (byte)val;
        }
    }

    private static void decodeUpFilter(byte[] curr, int coff,
                                       byte[] prev, int poff,
                                       int count) {
        for (int i = 0; i < count; i++) {
            int raw = curr[i + coff] & 0xff;
            int prior = prev[i + poff] & 0xff;

            curr[i + coff] = (byte)(raw + prior);
        }
    }

    private static void decodeAverageFilter(byte[] curr, int coff,
                                            byte[] prev, int poff,
                                            int count, int bpp) {
        int raw, priorPixel, priorRow;

        for (int i = 0; i < bpp; i++) {
            raw = curr[i + coff] & 0xff;
            priorRow = prev[i + poff] & 0xff;

            curr[i + coff] = (byte)(raw + priorRow/2);
        }

        for (int i = bpp; i < count; i++) {
            raw = curr[i + coff] & 0xff;
            priorPixel = curr[i + coff - bpp] & 0xff;
            priorRow = prev[i + poff] & 0xff;

            curr[i + coff] = (byte)(raw + (priorPixel + priorRow)/2);
        }
    }

    /**
      * paethpredictor。
     * @param a a
     * @param b b
     * @param c c
     * @return paethPredictor的结果
     */
    private static int paethPredictor(int a, int b, int c) {
        int p = a + b - c;
        int pa = Math.abs(p - a);
        int pb = Math.abs(p - b);
        int pc = Math.abs(p - c);

        if ((pa <= pb) && (pa <= pc)) {
            return a;
        } else if (pb <= pc) {
            return b;
        } else {
            return c;
        }
    }

    private static void decodePaethFilter(byte[] curr, int coff,
                                          byte[] prev, int poff,
                                          int count, int bpp) {
        int raw, priorPixel, priorRow, priorRowPixel;

        for (int i = 0; i < bpp; i++) {
            raw = curr[i + coff] & 0xff;
            priorRow = prev[i + poff] & 0xff;

            curr[i + coff] = (byte)(raw + priorRow);
        }

        for (int i = bpp; i < count; i++) {
            raw = curr[i + coff] & 0xff;
            priorPixel = curr[i + coff - bpp] & 0xff;
            priorRow = prev[i + poff] & 0xff;
            priorRowPixel = prev[i + poff - bpp] & 0xff;

            curr[i + coff] = (byte)(raw + paethPredictor(priorPixel,
                                                         priorRow,
                                                         priorRowPixel));
        }
    }

    /** Bandoffsets */
    private static final int[][] bandOffsets = {
        null,
        // 灰度（G）
        { 0 },
        // 灰度+透明（GA 顺序）
        { 0, 1 },
        // RGB 顺序
        { 0, 1, 2 },
        // RGBA 顺序
        { 0, 1, 2, 3 }
    };

    /**
     * 创建Raster
     * @param width width
     * @param height height
     * @param bands bands
     * @param scanlineStride scanlinestride
     * @param bitDepth 钻头深度
     */
    private WritableRaster createRaster(int width, int height, int bands,
                                        int scanlineStride,
                                        int bitDepth) {

        DataBuffer dataBuffer;
        WritableRaster ras = null;
        Point origin = new Point(0, 0);
        if ((bitDepth < 8) && (bands == 1)) {
            dataBuffer = new DataBufferByte(height*scanlineStride);
            ras = Raster.createPackedRaster(dataBuffer,
                                            width, height,
                                            bitDepth,
                                            origin);
        } else if (bitDepth <= 8) {
            dataBuffer = new DataBufferByte(height*scanlineStride);
            ras = Raster.createInterleavedRaster(dataBuffer,
                                                 width, height,
                                                 scanlineStride,
                                                 bands,
                                                 bandOffsets[bands],
                                                 origin);
        } else {
            dataBuffer = new DataBufferUShort(height*scanlineStride);
            ras = Raster.createInterleavedRaster(dataBuffer,
                                                 width, height,
                                                 scanlineStride,
                                                 bands,
                                                 bandOffsets[bands],
                                                 origin);
        }

        return ras;
    }

    /**
      * 跳过通过
     * @param passWidth 通过width
     * @param passHeight 通过height
     */
    private void skipPass(int passWidth, int passHeight)
        throws IOException {
        if ((passWidth == 0) || (passHeight == 0)) {
            return;
        }

        int inputBands = inputBandsForColorType[metadata.IHDR_colorType];
        int bitsPerRow = Math.
                multiplyExact((inputBands * metadata.IHDR_bitDepth), passWidth);
        int bytesPerRow = (bitsPerRow + 7) / 8;

 // 读取 the 镜像 row-by-row
        for (int srcY = 0; srcY < passHeight; srcY++) {
 // 跳过 过滤器 byte 和 the remaining row bytes
            pixelStream.skipBytes(1 + bytesPerRow);
        }
    }

    /**
      * 更新镜像进步
     * @param newPixels 新pixels
     */
    private void updateImageProgress(int newPixels) {
        pixelsDone += newPixels;
        processImageProgress(100.0F*pixelsDone/totalPixels);
    }

    /**
      * 解码通过
     * @param passNum 通过num
     * @param xStart x启动
     * @param yStart y启动
     * @param xStep xstep
     * @param yStep ystep
     * @param passWidth 通过width
     * @param passHeight 通过height
     */
    private void decodePass(int passNum,
                            int xStart, int yStart,
                            int xStep, int yStep,
                            int passWidth, int passHeight) throws IOException {

        if ((passWidth == 0) || (passHeight == 0)) {
            return;
        }

        WritableRaster imRas = theImage.getWritableTile(0, 0);
        int dstMinX = imRas.getMinX();
        int dstMaxX = dstMinX + imRas.getWidth() - 1;
        int dstMinY = imRas.getMinY();
        int dstMaxY = dstMinY + imRas.getHeight() - 1;

 // Determine which pixels will be 更新 入 this 通过
        int[] vals =
          ReaderUtils.computeUpdatedPixels(sourceRegion,
                                          destinationOffset,
                                          dstMinX, dstMinY,
                                          dstMaxX, dstMaxY,
                                          sourceXSubsampling,
                                          sourceYSubsampling,
                                          xStart, yStart,
                                          passWidth, passHeight,
                                          xStep, yStep);
        int updateMinX = vals[0];
        int updateMinY = vals[1];
        int updateWidth = vals[2];
        int updateXStep = vals[4];
        int updateYStep = vals[5];

        int bitDepth = metadata.IHDR_bitDepth;
        int inputBands = inputBandsForColorType[metadata.IHDR_colorType];
        int bytesPerPixel = (bitDepth == 16) ? 2 : 1;
        bytesPerPixel *= inputBands;

        int bitsPerRow = Math.multiplyExact((inputBands * bitDepth), passWidth);
        int bytesPerRow = (bitsPerRow + 7) / 8;
        int eltsPerRow = (bitDepth == 16) ? bytesPerRow/2 : bytesPerRow;

 // If no pixels need 更新, just 跳过 the 输入 数据
        if (updateWidth == 0) {
            for (int srcY = 0; srcY < passHeight; srcY++) {
 // 更新 数量 的 pixels 读取
                updateImageProgress(passWidth);
                /*
                  * If 读取 是否包含 been aborted, just 返回
                  * 处理读取aborted will be called later
                 */
                if (abortRequested()) {
                    return;
                }
 // 跳过 过滤器 byte 和 the remaining row bytes
                pixelStream.skipBytes(1 + bytesPerRow);
            }
            return;
        }

 // Backwards 映射 从 目标 pixels
        // (dstX = updateMinX + k*updateXStep)
        // to source pixels (sourceX), and then
        // to offset and skip in passRow (srcX and srcXStep)
        int sourceX =
            (updateMinX - destinationOffset.x)*sourceXSubsampling +
            sourceRegion.x;
        int srcX = (sourceX - xStart)/xStep;

 // Compute the step factor 入 the 源
        int srcXStep = updateXStep*sourceXSubsampling/xStep;

        byte[] byteData = null;
        short[] shortData = null;
        byte[] curr = new byte[bytesPerRow];
        byte[] prior = new byte[bytesPerRow];

 // 创建 a 1-row tall Raster 转为 hold the 数据
        WritableRaster passRow = createRaster(passWidth, 1, inputBands,
                                              eltsPerRow,
                                              bitDepth);

 // 创建 an array suitable for holding one pixel
        int[] ps = passRow.getPixel(0, 0, (int[])null);

        DataBuffer dataBuffer = passRow.getDataBuffer();
        int type = dataBuffer.getDataType();
        if (type == DataBuffer.TYPE_BYTE) {
            byteData = ((DataBufferByte)dataBuffer).getData();
        } else {
            shortData = ((DataBufferUShort)dataBuffer).getData();
        }

        processPassStarted(theImage,
                           passNum,
                           sourceMinProgressivePass,
                           sourceMaxProgressivePass,
                           updateMinX, updateMinY,
                           updateXStep, updateYStep,
                           destinationBands);

 // 处理 源 和 目标 bands
        if (sourceBands != null) {
            passRow = passRow.createWritableChild(0, 0,
                                                  passRow.getWidth(), 1,
                                                  0, 0,
                                                  sourceBands);
        }
        if (destinationBands != null) {
            imRas = imRas.createWritableChild(0, 0,
                                              imRas.getWidth(),
                                              imRas.getHeight(),
                                              0, 0,
                                              destinationBands);
        }

 // Determine if 全部 的 the relevant 输出 bands have the
 // same 钻头 深度 as the 源 数据
        boolean adjustBitDepths = false;
        int[] outputSampleSize = imRas.getSampleModel().getSampleSize();
        for (int b = 0; b < inputBands; b++) {
            if (outputSampleSize[b] != bitDepth) {
                adjustBitDepths = true;
                break;
            }
        }

 // If the 钻头 深度 differ, 创建 a lookup table per band 转为 执行
 // the 转换
        int[][] scale = null;
        if (adjustBitDepths) {
            int maxInSample = (1 << bitDepth) - 1;
            int halfMaxInSample = maxInSample/2;
            scale = new int[inputBands][];
            for (int b = 0; b < inputBands; b++) {
                int maxOutSample = (1 << outputSampleSize[b]) - 1;
                scale[b] = new int[maxInSample + 1];
                for (int s = 0; s <= maxInSample; s++) {
                    scale[b][s] =
                        (s*maxOutSample + halfMaxInSample)/maxInSample;
                }
            }
        }

 // 限制 通过row 转为 relevant area for the 大小写 where we
 // will 能否 设置rect 转为 副本 a contiguous span
        boolean useSetRect = srcXStep == 1 &&
            updateXStep == 1 &&
            !adjustBitDepths &&
            ("sun.awt.image.ByteInterleavedRaster".equals(imRas.getClass().getName()));

        if (useSetRect) {
            passRow = passRow.createWritableChild(srcX, 0,
                                                  updateWidth, 1,
                                                  0, 0,
                                                  null);
        }

        // Decode the (sub)image row-by-row
        for (int srcY = 0; srcY < passHeight; srcY++) {
 // 更新 数量 的 pixels 读取
            updateImageProgress(passWidth);
            /*
              * If 读取 是否包含 been aborted, just 返回
              * 处理读取aborted will be called later
             */
            if (abortRequested()) {
                return;
            }
 // 读取 the 过滤器 类型 byte 和 a row 的 数据
            int filter = pixelStream.read();
            try {
 // 掉期 curr 和 prior
                byte[] tmp = prior;
                prior = curr;
                curr = tmp;

                pixelStream.readFully(curr, 0, bytesPerRow);
            } catch (java.util.zip.ZipException ze) {
                throw new java.io.IOException("PNG pixel row read failed: " + ze.getMessage(), ze);
            }

            switch (filter) {
            case PNG_FILTER_NONE:
                break;
            case PNG_FILTER_SUB:
                decodeSubFilter(curr, 0, bytesPerRow, bytesPerPixel);
                break;
            case PNG_FILTER_UP:
                decodeUpFilter(curr, 0, prior, 0, bytesPerRow);
                break;
            case PNG_FILTER_AVERAGE:
                decodeAverageFilter(curr, 0, prior, 0, bytesPerRow,
                                    bytesPerPixel);
                break;
            case PNG_FILTER_PAETH:
                decodePaethFilter(curr, 0, prior, 0, bytesPerRow,
                                  bytesPerPixel);
                break;
            default:
                throw new IIOException("Unknown row filter type (= " +
                                       filter + ")!");
            }

 // 副本 数据 into 通过row byte by byte
            if (bitDepth < 16) {
                System.arraycopy(curr, 0, byteData, 0, bytesPerRow);
            } else {
                int idx = 0;
                for (int j = 0; j < eltsPerRow; j++) {
                    shortData[j] =
                        (short)((curr[idx] << 8) | (curr[idx + 1] & 0xff));
                    idx += 2;
                }
            }

 // True Y 位置 入 源
            int sourceY = srcY*yStep + yStart;
            if ((sourceY >= sourceRegion.y) &&
                (sourceY < sourceRegion.y + sourceRegion.height) &&
                (((sourceY - sourceRegion.y) %
                  sourceYSubsampling) == 0)) {

                int dstY = destinationOffset.y +
                    (sourceY - sourceRegion.y)/sourceYSubsampling;
                if (dstY < dstMinY) {
                    continue;
                }
                if (dstY > dstMaxY) {
                    break;
                }

               /*
                 * For PNG 镜像 的 color 类型 PNG_COLOR_RGB 或 PNG_COLOR_GRAY
                 * that contain a 特定 transparent color (given by trns
                * chunk), we compare the decoded pixel color with the color
                 * given by trns chunk 转为 设置 the alpha on the 目标.
                */
                boolean tRNSTransparentPixelPresent =
                    theImage.getSampleModel().getNumBands() == inputBands + 1 &&
                    metadata.hasTransparentColor();
                if (useSetRect &&
                    !tRNSTransparentPixelPresent) {
                    imRas.setRect(updateMinX, dstY, passRow);
                } else {
                    int newSrcX = srcX;

                    /*
                      * 创建 intermediate array 转为 fill the extra alpha
                      * 通道 When.js trnstransparentpixelpresent 是否 true.
                     */
                    final int[] temp = new int[inputBands + 1];
                    final int opaque = (bitDepth < 16) ? 255 : 65535;
                    for (int dstX = updateMinX;
                         dstX < updateMinX + updateWidth;
                         dstX += updateXStep) {

                        passRow.getPixel(newSrcX, 0, ps);
                        if (adjustBitDepths) {
                            for (int b = 0; b < inputBands; b++) {
                                ps[b] = scale[b][ps[b]];
                            }
                        }
                        if (tRNSTransparentPixelPresent) {
                            if (metadata.tRNS_colorType == PNG_COLOR_RGB) {
                                temp[0] = ps[0];
                                temp[1] = ps[1];
                                temp[2] = ps[2];
                                if (ps[0] == metadata.tRNS_red &&
                                    ps[1] == metadata.tRNS_green &&
                                    ps[2] == metadata.tRNS_blue) {
                                    temp[3] = 0;
                                } else {
                                    temp[3] = opaque;
                                }
                            } else {
 // When.js.js trns_color类型 是否 PNG_COLOR_GRAY
                                temp[0] = ps[0];
                                if (ps[0] == metadata.tRNS_gray) {
                                    temp[1] = 0;
                                } else {
                                    temp[1] = opaque;
                                }
                            }
                            imRas.setPixel(dstX, dstY, temp);
                        } else {
                            imRas.setPixel(dstX, dstY, ps);
                        }
                        newSrcX += srcXStep;
                    }
                }

                processImageUpdate(theImage,
                                   updateMinX, dstY,
                                   updateWidth, 1,
                                   updateXStep, updateYStep,
                                   destinationBands);
            }
        }

        processPassComplete(theImage);
    }

    /**
      * 解码镜像
     * @param width width
     * @param height height
     */
    private void decodeImage(int width, int height)
        throws IOException {

        this.pixelsDone = 0;
        this.totalPixels = width*height;

        if (metadata.IHDR_interlaceMethod == 0) {
            decodePass(0, 0, 0, 1, 1, width, height);
        } else {
            for (int i = 0; i <= sourceMaxProgressivePass; i++) {
                int XOffset = adam7XOffset[i];
                int YOffset = adam7YOffset[i];
                int XSubsampling = adam7XSubsampling[i];
                int YSubsampling = adam7YSubsampling[i];
                int xbump = adam7XSubsampling[i + 1] - 1;
                int ybump = adam7YSubsampling[i + 1] - 1;

                if (i >= sourceMinProgressivePass) {
                    decodePass(i,
                               XOffset,
                               YOffset,
                               XSubsampling,
                               YSubsampling,
                               (width + xbump)/XSubsampling,
                               (height + ybump)/YSubsampling);
                } else {
                    skipPass((width + xbump)/XSubsampling,
                             (height + ybump)/YSubsampling);
                }

                /*
                  * If 读取 是否包含 been aborted, just 返回
                  * 处理读取aborted will be called later
                 */
                if (abortRequested()) {
                    return;
                }
            }
        }
    }

    /**
      * 读取镜像
     * @param imageIndex 镜像索引
     * @param param 参数
     */
    private void readImage(int imageIndex, ImageReadParam param) throws IIOException {
        readMetadata();

        if (!isAnimated && imageIndex != 0) {
            throw new IndexOutOfBoundsException("imageIndex != 0!");
        }

        boolean isAnimated = this.isAnimated;
        if (param != null && ((PNGImageReadParam) param).isForceReadIDAT()) {
            isAnimated = false;
        }
        int width, height;
        if (isAnimated) {
            PNGMetadata metadata = frameMetadata.get(imageIndex);
            if (metadata == null) {
                throw new IIOException("Frame metadata not exist!");
            }
            width = metadata.fcTL_width;
            height = metadata.fcTL_height;
        } else {
            width = metadata.IHDR_width;
            height = metadata.IHDR_height;
        }

        if ((long)width * height > Integer.MAX_VALUE - 2) {
 // We are not able 转为 properly decode 镜像 that 是否包含 数字
 // 的 pixels greater than Integer.最大_值 - 2
            throw new IIOException("Can not read image of the size "
                    + width + " by " + height);
        }

 // 初始化 默认 值
        sourceXSubsampling = 1;
        sourceYSubsampling = 1;
        sourceMinProgressivePass = 0;
        sourceMaxProgressivePass = 6;
        sourceBands = null;
        destinationBands = null;
        destinationOffset = new Point(0, 0);

 // If an 镜像读取参数 是否 可用, 获取 值 从 it
        if (param != null) {
            sourceXSubsampling = param.getSourceXSubsampling();
            sourceYSubsampling = param.getSourceYSubsampling();

            sourceMinProgressivePass =
                Math.max(param.getSourceMinProgressivePass(), 0);
            sourceMaxProgressivePass =
                Math.min(param.getSourceMaxProgressivePass(), 6);

            sourceBands = param.getSourceBands();
            destinationBands = param.getDestinationBands();
            destinationOffset = param.getDestinationOffset();
        }
        Inflater inf = null;
        try {
            boolean fdAT = false;
            long position = imageStartPosition;
            if (isAnimated && !(imageIndex == 0 && animContainsIDAT)) {
                position = frameImageStartPositions.get(imageIndex);
                fdAT = true;
            }
            stream.seek(position);

            Enumeration<InputStream> e = new PNGImageDataEnumeration(stream, fdAT);
            InputStream is = new SequenceInputStream(e);

           /* InflaterInputStream uses an Inflater instance which consumes
             * NAT (non-GC visible) resources. This 是否 normally implicitly
             * freed When.js the 流 是否 关闭. However 自 the
             * inflater输入流 wraps a 客户端-supplied 输入 流,
             * we cannot 关闭 it.
             * But the app may depend on GC finalization 转为 关闭 the 流.
             * Therefore 转为 ensure 时间 freeing 的 NAT resources we
             * explicitly 创建 the Inflater instance 和 free its resources
             * When.js we are done with the inflater输入流 by calling
             * inf.结束();
            */
            inf = new Inflater();
            is = new InflaterInputStream(is, inf);
            is = new BufferedInputStream(is);
            this.pixelStream = new DataInputStream(is);

            /*
              * PNG spec declares that valid 范围 for width
              * 和 height 是否 [1, 2^31-1], so here we may 失败 转为 allocate
              * a 缓冲 for 目标 镜像 due 转为 内存 limitation.
             *
              * If the 读取 operation triggers 出的内存错误, the same
              * will be wrapped 入 an iio异常 at png镜像读取.读取
              * 方法.
             *
              * The recovery strategy for this 大小写 should be defined at
              * the 级别 的 application, so we will not 尝试 转为 estimate
              * the required amount 的 the 内存 和/或 处理 OOM 入
              * 任意 way.
             */
            theImage = getDestination(param,
                                      getImageTypes(0),
                                      width,
                                      height);

            Rectangle destRegion = new Rectangle(0, 0, 0, 0);
            sourceRegion = new Rectangle(0, 0, 0, 0);
            computeRegions(param, width, height,
                           theImage,
                           sourceRegion, destRegion);
            destinationOffset.setLocation(destRegion.getLocation());

 // At this point the 头部 是否包含 been 读取 和 we know
 // how many bands are 入 the 镜像, so 执行 检查
 // 的 the 读取 参数.
            int colorType = metadata.IHDR_colorType;
            if (theImage.getSampleModel().getNumBands()
                == inputBandsForColorType[colorType] + 1
                && metadata.hasTransparentColor()) {
                checkReadParamBandSettings(param,
                    inputBandsForColorType[colorType] + 1,
                    theImage.getSampleModel().getNumBands());
            } else {
                checkReadParamBandSettings(param,
                    inputBandsForColorType[colorType],
                    theImage.getSampleModel().getNumBands());
            }

            clearAbortRequest();
            processImageStarted(0);
            if (abortRequested()) {
                processReadAborted();
            } else {
                decodeImage(width, height);
                if (abortRequested()) {
                    processReadAborted();
                } else {
                    processImageComplete();
                }
            }

        } catch (IOException e) {
            throw new IIOException("Error reading PNG image data", e);
        } finally {
            if (inf != null) {
                inf.end();
            }
        }
    }

    @Override
    /**
      * 获取num镜像
     * @param allowSearch allow搜索
     */
    public int getNumImages(boolean allowSearch) throws IIOException {
        if (stream == null) {
            throw new IllegalStateException("No input source set!");
        }
        if (seekForwardOnly && allowSearch) {
            throw new IllegalStateException
                ("seekForwardOnly and allowSearch can't both be true!");
        }
        readMetadata();
        return isAnimated ? metadata.acTL_num_frames : 1;
    }

    @Override
    /**
     * 获取Width
     * @param imageIndex 镜像索引
     */
    public int getWidth(int imageIndex) throws IIOException {

        readMetadata();

        if (isAnimated) {
            PNGMetadata metadata = frameMetadata.get(imageIndex);
            if (metadata == null) {
                throw new IIOException("No image metadata exist this index: " + imageIndex);
            }
            return metadata.fcTL_width;
        } else if (imageIndex != 0) {
            throw new IndexOutOfBoundsException("imageIndex != 0!");
        }

        return metadata.IHDR_width;
    }

    @Override
    /**
     * 获取Height
     * @param imageIndex 镜像索引
     */
    public int getHeight(int imageIndex) throws IIOException {

        readMetadata();

        if (isAnimated) {
            PNGMetadata metadata = frameMetadata.get(imageIndex);
            if (metadata == null) {
                throw new IIOException("No image metadata exist this index: " + imageIndex);
            }
            return metadata.fcTL_height;
        } else if (imageIndex != 0) {
            throw new IndexOutOfBoundsException("imageIndex != 0!");
        }

        return metadata.IHDR_height;
    }

    @Override
    /**
      * 获取镜像类型
     * @param imageIndex 镜像索引
     */
    public Iterator<ImageTypeSpecifier> getImageTypes(int imageIndex)
      throws IIOException
    {

        readMetadata();

        if (!isAnimated && imageIndex != 0) {
            throw new IndexOutOfBoundsException("imageIndex != 0!");
        }

        ArrayList<ImageTypeSpecifier> l =
            new ArrayList<ImageTypeSpecifier>(1);

        ColorSpace rgb;
        ColorSpace gray;
        int[] bandOffsets;

        int bitDepth = metadata.IHDR_bitDepth;
        int colorType = metadata.IHDR_colorType;

        int dataType;
        if (bitDepth <= 8) {
            dataType = DataBuffer.TYPE_BYTE;
        } else {
            dataType = DataBuffer.TYPE_USHORT;
        }

        switch (colorType) {
        /*
          * For PNG 镜像 的 color 类型 PNG_COLOR_RGB 或 PNG_COLOR_GRAY that
          * contain a 特定 transparent color (given by trns chunk), we 添加
          * 镜像类型specifier(s) that 支持 transparency 转为 the 列表 的
          * 支持 镜像 类型.
         */
        case PNG_COLOR_GRAY:
 // Need trns chunk
            readMetadata();

            if (metadata.hasTransparentColor()) {
                gray = ColorSpace.getInstance(ColorSpace.CS_GRAY);
                bandOffsets = new int[2];
                bandOffsets[0] = 0;
                bandOffsets[1] = 1;
                l.add(ImageTypeSpecifier.createInterleaved(gray,
                                                           bandOffsets,
                                                           dataType,
                                                           true,
                                                           false));
            }
            // Packed grayscale
            l.add(ImageTypeSpecifier.createGrayscale(bitDepth,
                                                     dataType,
                                                     false));
            break;

        case PNG_COLOR_RGB:
 // Need trns chunk
            readMetadata();

            if (bitDepth == 8) {
                if (metadata.hasTransparentColor()) {
                    l.add(ImageTypeSpecifier.createFromBufferedImageType(
                            BufferedImage.TYPE_4BYTE_ABGR));
                }
 // some 标准 类型 的 缓冲 镜像
 // which 能否 be used as 目标
                l.add(ImageTypeSpecifier.createFromBufferedImageType(
                          BufferedImage.TYPE_3BYTE_BGR));

                l.add(ImageTypeSpecifier.createFromBufferedImageType(
                          BufferedImage.TYPE_INT_RGB));

                l.add(ImageTypeSpecifier.createFromBufferedImageType(
                          BufferedImage.TYPE_INT_BGR));

            }

            if (metadata.hasTransparentColor()) {
                rgb = ColorSpace.getInstance(ColorSpace.CS_sRGB);
                bandOffsets = new int[4];
                bandOffsets[0] = 0;
                bandOffsets[1] = 1;
                bandOffsets[2] = 2;
                bandOffsets[3] = 3;

                l.add(ImageTypeSpecifier.
                    createInterleaved(rgb, bandOffsets,
                                      dataType, true, false));
            }
 // 组件 R, G, B
            rgb = ColorSpace.getInstance(ColorSpace.CS_sRGB);
            bandOffsets = new int[3];
            bandOffsets[0] = 0;
            bandOffsets[1] = 1;
            bandOffsets[2] = 2;
            l.add(ImageTypeSpecifier.createInterleaved(rgb,
                                                       bandOffsets,
                                                       dataType,
                                                       false,
                                                       false));
            break;

        case PNG_COLOR_PALETTE:
 // Need trns chunk
            readMetadata();

            /*
             * The PLTE chunk spec says:
             *
              * The 数字 的 palette entries must not exceed the 范围 that
              * 能否 be represented 入 the 镜像 钻头 深度 (for example, 2^4 = 16
              * for a 钻头 深度 的 4). It 是否 permissible 转为 have fewer entries
              * than the 钻头 深度 would allow. 入 that 大小写, 任意 出-的-范围
              * pixel 值 found 入 the 镜像 数据 是否 an 错误.
             *
             * http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html#C.PLTE
             *
              * Consequently, the 大小写 When.js the palette 长度 是否 smaller than
              * 2^钻头深度 是否 legal 入 the view 的 PNG spec.
             *
              * However the spec 的 创建索引() 方法 demands the exact
              * equality 的 the palette lengh 和 数字 的 possible palette
              * entries (2^钻头深度).
             *
             * {@link javax.imageio.ImageTypeSpecifier.html#createIndexed}
             *
              * 入 订单 转为 avoid this contradiction we need 转为 extend the
              * palette arrays 转为 the 限制 defined by the 钻头深度.
             */

            int plength = 1 << bitDepth;

            byte[] red = metadata.PLTE_red;
            byte[] green = metadata.PLTE_green;
            byte[] blue = metadata.PLTE_blue;

            if (metadata.PLTE_red.length < plength) {
                red = Arrays.copyOf(metadata.PLTE_red, plength);
                Arrays.fill(red, metadata.PLTE_red.length, plength,
                            metadata.PLTE_red[metadata.PLTE_red.length - 1]);

                green = Arrays.copyOf(metadata.PLTE_green, plength);
                Arrays.fill(green, metadata.PLTE_green.length, plength,
                            metadata.PLTE_green[metadata.PLTE_green.length - 1]);

                blue = Arrays.copyOf(metadata.PLTE_blue, plength);
                Arrays.fill(blue, metadata.PLTE_blue.length, plength,
                            metadata.PLTE_blue[metadata.PLTE_blue.length - 1]);

            }

 // Alpha 从 trns chunk may have fewer entries than
 // the RGB luts 从 the PLTE chunk; if so, pad with
            // 255.
            byte[] alpha = null;
            if (metadata.tRNS_present && (metadata.tRNS_alpha != null)) {
                if (metadata.tRNS_alpha.length == red.length) {
                    alpha = metadata.tRNS_alpha;
                } else {
                    alpha = Arrays.copyOf(metadata.tRNS_alpha, red.length);
                    Arrays.fill(alpha,
                                metadata.tRNS_alpha.length,
                                red.length, (byte)255);
                }
            }

            l.add(ImageTypeSpecifier.createIndexed(red, green,
                                                   blue, alpha,
                                                   bitDepth,
                                                   DataBuffer.TYPE_BYTE));
            break;

        case PNG_COLOR_GRAY_ALPHA:
 // 组件 G, A
            gray = ColorSpace.getInstance(ColorSpace.CS_GRAY);
            bandOffsets = new int[2];
            bandOffsets[0] = 0;
            bandOffsets[1] = 1;
            l.add(ImageTypeSpecifier.createInterleaved(gray,
                                                       bandOffsets,
                                                       dataType,
                                                       true,
                                                       false));
            break;

        case PNG_COLOR_RGB_ALPHA:
            if (bitDepth == 8) {
 // some 标准 类型 的 缓冲 镜像
 // wich 能否 be used as 目标
                l.add(ImageTypeSpecifier.createFromBufferedImageType(
                          BufferedImage.TYPE_4BYTE_ABGR));

                l.add(ImageTypeSpecifier.createFromBufferedImageType(
                          BufferedImage.TYPE_INT_ARGB));
            }

            // Component R, G, B, A (non-premultiplied)
            rgb = ColorSpace.getInstance(ColorSpace.CS_sRGB);
            bandOffsets = new int[4];
            bandOffsets[0] = 0;
            bandOffsets[1] = 1;
            bandOffsets[2] = 2;
            bandOffsets[3] = 3;

            l.add(ImageTypeSpecifier.createInterleaved(rgb,
                                                       bandOffsets,
                                                       dataType,
                                                       true,
                                                       false));
            break;

        default:
            break;
        }

        return l.iterator();
    }

    /*
      * 父 类 implementation uses 第一个 element
      * 的 镜像 类型 列表 as raw 镜像 类型.
     *
      * Also, 父 implementation uses 第一个 element 的 this 列表
      * as 默认 目标 类型 镜像 读取 参数 执行 not specify
     * anything other.
     *
      * However, 入 大小写 的 RGB 和 RGBA color 类型, raw 镜像 类型
      * produces 缓冲 镜像 的 习俗 类型. It causes some
      * 表现 degradation 的 subsequent rendering operations.
     *
      * 转为 resolve this contradiction we 放入 标准 镜像 类型
      * at the 第一个 位置 的 镜像 类型 列表 (转为 produce 标准
      * 镜像 by 默认) 和 放入 raw 镜像 类型 (which 是否 习俗)
      * at the 最后一个 位置 的 this 列表.
     *
      * 之后 this 改变 we should override 获取raw镜像类型()
      * 转为 返回 最后一个 element 的 镜像 类型 列表.
     */
    @Override
    public ImageTypeSpecifier getRawImageType(int imageIndex)
      throws IOException {

        Iterator<ImageTypeSpecifier> types = getImageTypes(imageIndex);
        ImageTypeSpecifier raw = null;
        do {
            raw = types.next();
        } while (types.hasNext());
        return raw;
    }

    @Override
    /** 获取默认读取参数 */
    public ImageReadParam getDefaultReadParam() {
        
        return new PNGImageReadParam();
    
    }

    @Override
    /** 获取流式输出Metadata */
    public IIOMetadata getStreamMetadata()
        throws IIOException {
        return null;
    }

    @Override
    /**
      * 获取镜像metadata
     * @param imageIndex 镜像索引
     */
    public IIOMetadata getImageMetadata(int imageIndex) throws IIOException {
        readMetadata();

        if (isAnimated) {
            PNGMetadata metadata = frameMetadata.get(imageIndex);
            if (metadata == null) {
                throw new IIOException("No image metadata exist for this index: " + imageIndex);
            }
            return metadata;
        } else if (imageIndex != 0) {
            throw new IndexOutOfBoundsException("imageIndex != 0!");
        }

        return metadata;
    }

    @Override
    /**
     * 读取
     * @param imageIndex 镜像索引
     * @param param 参数
     */
    public BufferedImage read(int imageIndex, ImageReadParam param)
        throws IIOException {

        try {
            readImage(imageIndex, param);
        } catch (IOException |
                 IllegalStateException |
                 IllegalArgumentException e)
        {
            throw e;
        } catch (Throwable e) {
            throw new IIOException("Caught exception during read: ", e);
        }
        return theImage;
    }

    @Override
    /** Reset */
    public void reset() {
        super.reset();
        resetStreamSettings();
    }

    /** Reset流式输出Settings */
    private void resetStreamSettings() {
        gotHeader = false;
        gotMetadata = false;
        metadata = null;
        pixelStream = null;
        imageStartPosition = -1L;
        frameImageStartPositions.clear();
        frameMetadata.clear();
        isAnimated = false;
        nextImageIndex = 0;
        animContainsIDAT = false;
    }
}

