<?xml version='1.0' encoding='utf-8'?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.chua</groupId>
        <artifactId>utils-support-parent-starter</artifactId>
        <version>4.0.0.42</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>utils-support-gateway-parent</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>utils-support-gateway-controller-starter</module>
        <module>utils-support-gateway-server-starter</module>
        <module>utils-support-gateway-agent-starter</module>
    </modules>
    <build>
        <plugins>

        </plugins>
    </build>
</project>
