<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.chua</groupId>
        <artifactId>utils-support-extra-parent</artifactId>
        <version>4.0.0.42</version>
    </parent>

    <artifactId>utils-support-serialize-starter</artifactId>
    <packaging>jar</packaging>

    <name>utils-support-serialize-starter</name>
    <description>序列化支持模块，提供 Kryo、JSON、Java 等多种序列化方式及自动序列化能力。</description>

    <properties>
        <maven.compiler.useIncrementalCompilation>false</maven.compiler.useIncrementalCompilation>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.chua</groupId>
            <artifactId>utils-support-common-starter</artifactId>
            <version>4.0.0.42</version>
        </dependency>
        <dependency>
            <groupId>com.esotericsoftware</groupId>
            <artifactId>kryo</artifactId>
        </dependency>
    </dependencies>
</project>
